{
 "title": "Global",
 "description": "This is a modern 'Global View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_cpu_seconds_total{ cluster=~\"$cluster\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "description": "Displays actual CPU usage along with requested and limited CPU across the cluster in percentage.\n\n",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=~\"$cluster\", job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "avg(sum by (core) (rate(windows_cpu_time_total{mode!=\"idle\", cluster=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "Real Windows"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", cluster=~\"$cluster\"}) / sum(machine_cpu_cores{ cluster=~\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=~\"$cluster\"}) / sum(machine_cpu_cores{ cluster=~\"$cluster\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "description": "Shows the real memory usage along with memory requests and limits for all workloads in percentage .\n\n",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{ cluster=~\"$cluster\", job=\"$job\"} - node_memory_MemAvailable_bytes{ cluster=~\"$cluster\", job=\"$job\"}) / sum(node_memory_MemTotal_bytes{ cluster=~\"$cluster\", job=\"$job\"})",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(windows_memory_available_bytes{ cluster=~\"$cluster\"} + windows_memory_cache_bytes{ cluster=~\"$cluster\"}) / sum(windows_os_visible_memory_bytes{ cluster=~\"$cluster\"})",
     "legendFormat": "Real Windows"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=~\"$cluster\"}) / sum(machine_memory_bytes{ cluster=~\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=~\"$cluster\"}) / sum(machine_memory_bytes{ cluster=~\"$cluster\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Total number of Kubernetes nodes currently part of the cluster.\n\n",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info{ cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "description": "Provides the count of key Kubernetes resources like pods, services, secrets, and volumes over time.\n\n",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_namespace_labels{ cluster=~\"$cluster\"})",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "sum(kube_pod_container_status_running{ cluster=~\"$cluster\"})",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", cluster=~\"$cluster\"})",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_service_info{ cluster=~\"$cluster\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_endpoint_info{ cluster=~\"$cluster\"})",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "sum(kube_ingress_info{ cluster=~\"$cluster\"})",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_deployment_labels{ cluster=~\"$cluster\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_labels{ cluster=~\"$cluster\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_labels{ cluster=~\"$cluster\"})",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{ cluster=~\"$cluster\"})",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{ cluster=~\"$cluster\"})",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{ cluster=~\"$cluster\"})",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(kube_secret_info{ cluster=~\"$cluster\"})",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(kube_networkpolicy_labels{ cluster=~\"$cluster\"})",
     "legendFormat": "Network Policies"
    },
    {
     "expr": "count(count by (node) (kube_node_info{ cluster=~\"$cluster\"}))",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "description": "Total count of namespaces in the cluster, representing isolated environments.\n\n",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{ cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "Shows actual CPU usage in cores, along with requested and limit values across the cluster.\n\n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=~\"$cluster\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(rate(windows_cpu_time_total{mode!=\"idle\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Real Windows"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", cluster=~\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=~\"$cluster\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_cpu_cores{ cluster=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "Displays actual RAM usage in GiB, along with requested and maximum allowed values.\n\n",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{ cluster=~\"$cluster\", job=\"$job\"} - node_memory_MemAvailable_bytes{ cluster=~\"$cluster\", job=\"$job\"})",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(windows_os_visible_memory_bytes{ cluster=~\"$cluster\"} - windows_memory_available_bytes{ cluster=~\"$cluster\"} - windows_memory_cache_bytes{ cluster=~\"$cluster\"})",
     "legendFormat": "Real Windows"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=~\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=~\"$cluster\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_memory_bytes{ cluster=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "description": "Indicates the total number of currently running pods in the cluster.\n\n",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", cluster=~\"$cluster\"})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "description": "Shows the overall CPU usage (%) of the whole Kubernetes cluster over time.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=~\"$cluster\", job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Linux"
    },
    {
     "expr": "1 - avg(rate(windows_cpu_time_total{ cluster=~\"$cluster\",mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Windows"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "description": "Displays the total memory usage (%) across the entire cluster over time.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{ cluster=~\"$cluster\", job=\"$job\"} - node_memory_MemAvailable_bytes{ cluster=~\"$cluster\", job=\"$job\"}) / sum(node_memory_MemTotal_bytes{ cluster=~\"$cluster\", job=\"$job\"})",
     "legendFormat": "Linux"
    },
    {
     "expr": "sum(windows_os_visible_memory_bytes{ cluster=~\"$cluster\"} - windows_memory_available_bytes{ cluster=~\"$cluster\"}) / sum(windows_os_visible_memory_bytes{ cluster=~\"$cluster\"})",
     "legendFormat": "Windows"
    }
   ]
  },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "description": "Shows how much CPU (in cores) each namespace is using over time.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", cluster=~\"$cluster\"}[$__rate_interval])) by (namespace)\n+ on (namespace)\n(sum(rate(windows_container_cpu_usage_seconds_total{container_id!=\"\", cluster=~\"$cluster\"}[$__rate_interval]) * on (container_id) group_left (container, pod, namespace) max by ( container, container_id, pod, namespace) (kube_pod_container_info{container_id!=\"\", cluster=~\"$cluster\"}) OR kube_namespace_created{ cluster=~\"$cluster\"} * 0) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "description": "Displays memory used (in GiB) by each namespace over time.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", cluster=~\"$cluster\"}) by (namespace)\n+ on (namespace)\n(sum(windows_container_memory_usage_commit_bytes{container_id!=\"\", cluster=~\"$cluster\"} * on (container_id) group_left (container, pod, namespace) max by ( container, container_id, pod, namespace) (kube_pod_container_info{container_id!=\"\", cluster=~\"$cluster\"}) OR kube_namespace_created{ cluster=~\"$cluster\"} * 0) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by instance",
   "type": "timeseries",
   "description": "Shows how much CPU (in %) is being used by each node (IP address) over time.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=~\"$cluster\", job=\"$job\"}[$__rate_interval]))) by (instance)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "avg(sum by (instance,core) (rate(windows_cpu_time_total{mode!=\"idle\", cluster=~\"$cluster\"}[$__rate_interval]))) by (instance)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by instance",
   "type": "timeseries",
   "description": "Displays the amount of memory (in GiB) used by each node in the cluster over time.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{ cluster=~\"$cluster\", job=\"$job\"} - node_memory_MemAvailable_bytes{ cluster=~\"$cluster\", job=\"$job\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(windows_os_visible_memory_bytes{ cluster=~\"$cluster\"} - windows_memory_available_bytes{ cluster=~\"$cluster\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Throttled seconds by namespace",
   "type": "timeseries",
   "description": "Indicates how much time containers in each namespace were throttled due to CPU limits.\nHigher values may mean CPU limits are too tight, causing performance issues.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{image!=\"\", cluster=~\"$cluster\"}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Kubernetes Pods QoS classes",
   "type": "timeseries",
   "description": "Shows how many pods fall into each Quality of Service (QoS) class:\n\nBestEffort: No resource requests or limits set\n\nBurstable: Requests and/or limits set for some containers\n\nGuaranteed: Requests and limits are equal for all containers in the pod\nAlso displays total pod count over time.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_qos_class{ cluster=~\"$cluster\"}) by (qos_class)",
     "legendFormat": "{{ qos_class }} pods"
    },
    {
     "expr": "sum(kube_pod_info{ cluster=~\"$cluster\"})",
     "legendFormat": "Total pods"
    }
   ]
  },
  {
   "title": "Kubernetes Pods Status Reason",
   "type": "timeseries",
   "description": "Displays reasons why pods failed to start or were removed.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason{ cluster=~\"$cluster\"}) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "OOM Events by namespace",
   "type": "timeseries",
   "description": "Shows how many times pods in each namespace were killed due to Out Of Memory (OOM).\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(container_oom_events_total[$__rate_interval])) by (namespace) >= 0\r\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Container Restarts by namespace",
   "type": "timeseries",
   "description": "Displays how many times containers restarted in each namespace.\nFrequent restarts may indicate application crashes or readiness issues.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{ cluster=~\"$cluster\"}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Global Network Utilization by device",
   "type": "timeseries",
   "description": "Shows how much data is being sent and received through each network device. Helps to identify which device is handling more network traffic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc).*\", cluster=~\"$cluster\", job=\"$job\"}[$__rate_interval])) by (device)",
     "legendFormat": "Received : {{ device }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc).*\", cluster=~\"$cluster\", job=\"$job\"}[$__rate_interval])) by (device)",
     "legendFormat": "Transmitted : {{ device }}"
    },
    {
     "expr": "sum(rate(windows_net_bytes_received_total{ cluster=~\"$cluster\"}[$__rate_interval])) by (nic)",
     "legendFormat": "Received : {{ nic }}"
    },
    {
     "expr": "- sum(rate(windows_net_bytes_sent_total{ cluster=~\"$cluster\"}[$__rate_interval])) by (nic)",
     "legendFormat": "Transmitted : {{ device }}"
    }
   ]
  },
  {
   "title": "Network Saturation - Packets dropped",
   "type": "timeseries",
   "description": "Displays the number of network packets that are dropped. Dropped packets may indicate network congestion or performance issues.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{ cluster=~\"$cluster\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Linux Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(node_network_transmit_drop_total{ cluster=~\"$cluster\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Linux Packets dropped (transmit)"
    },
    {
     "expr": "sum(rate(windows_net_packets_received_discarded_total{ cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Windows Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(windows_net_packets_outbound_discarded_total{ cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Windows Packets dropped (transmit)"
    }
   ]
  },
  {
   "title": "Network Received by namespace",
   "type": "timeseries",
   "description": "Shows how much network traffic (received data) each Kubernetes namespace is using. Helps identify high-traffic namespaces.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{ cluster=~\"$cluster\"}[$__rate_interval])) by (namespace)\n+ on (namespace)\n(sum(rate(windows_container_network_receive_bytes_total{container_id!=\"\", cluster=~\"$cluster\"}[$__rate_interval]) * on (container_id) group_left (container, pod, namespace) max by ( container, container_id, pod, namespace) (kube_pod_container_info{container_id!=\"\", cluster=~\"$cluster\"}) OR kube_namespace_created{ cluster=~\"$cluster\"} * 0) by (namespace))",
     "legendFormat": "Received : {{ namespace }}"
    },
    {
     "expr": "- (sum(rate(container_network_transmit_bytes_total{ cluster=~\"$cluster\"}[$__rate_interval])) by (namespace)\n+ on (namespace)\n(sum(rate(windows_container_network_transmit_bytes_total{container_id!=\"\", cluster=~\"$cluster\"}[$__rate_interval]) * on (container_id) group_left (container, pod, namespace) max by ( container, container_id, pod, namespace) (kube_pod_container_info{container_id!=\"\", cluster=~\"$cluster\"}) OR kube_namespace_created{ cluster=~\"$cluster\"} * 0) by (namespace)))",
     "legendFormat": "Transmitted : {{ namespace }}"
    }
   ]
  },
  {
   "title": "Total Network Received (with all virtual devices) by instance",
   "type": "timeseries",
   "description": "Displays total network data received on each server (including virtual interfaces). Useful for checking which instance is handling the most traffic.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{ cluster=~\"$cluster\", job=\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{ cluster=~\"$cluster\", job=\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    },
    {
     "expr": "sum(rate(windows_net_bytes_received_total{ cluster=~\"$cluster\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(windows_net_bytes_sent_total{ cluster=~\"$cluster\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  },
  {
   "title": "Network Received (without loopback)  by instance",
   "type": "timeseries",
   "description": "Shows real network data received by each instance, excluding internal (loopback) traffic. Helps monitor actual external network usage.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc|lo).*\", cluster=~\"$cluster\", job=\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc|lo).*\", cluster=~\"$cluster\", job=\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    },
    {
     "expr": "sum(rate(windows_net_bytes_received_total{nic!~\".*Virtual.*\", cluster=~\"$cluster\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(windows_net_bytes_sent_total{nic!~\".*Virtual.*\", cluster=~\"$cluster\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  },
  {
   "title": "Network Received (loopback only) by instance",
   "type": "timeseries",
   "description": "Displays data received only through the loopback interface (internal server communication). Useful to monitor in-node service traffic.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=\"lo\", cluster=~\"$cluster\", job=\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device=\"lo\", cluster=~\"$cluster\", job=\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  }
 ]
}