{
 "title": "Harbor Overview",
 "description": "Overview Dashboard for the open-source Harbor Image Repository",
 "tags": [ "harbor" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Harbor instance",
    "query": {
     "query": "label_values(harbor_system_info,instance)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(harbor_project_artifact_total{instance=~\"$instance\"},project_name)"
    }
   },
   {
    "name": "Role",
    "label": "role",
    "query": {
     "query": "label_values(harbor_system_info,role)"
    }
   },
   { "name": "DATASOURCE", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "System info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"harbor-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Auth mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_system_info{job=\"harbor-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_health{instance=~\"$instance\",job=\"harbor-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Job  Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_health{instance=~\"$instance\",job=\"harbor-metrics\" , role=\"$Role\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Replication  Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_task_queue_latency{type=~\"REPLICATION|IMAGE_REPLICATE\", role=~\"$Role\"}\r\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Job Queue Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (harbor_task_queue_size {role=\"$Role\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retention Job",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_task_queue_latency{type=\"RETENTION\" , role=\"$Role\"}\r\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Component status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Component status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{instance=~\"$instance\",job=\"harbor-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Projects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total projects",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (harbor_project_total{instance=~\"$instance\",job=\"harbor-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New projects last 24h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(harbor_project_total{instance=~\"$instance\", job=\"harbor-metrics\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Project type",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (harbor_project_total{instance=~\"$instance\",job=\"harbor-exporter\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (public)(harbor_project_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (harbor_project_quota_usage_byte{instance=~\"$instance\",job=\"harbor-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repositories by project",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (project_name)(harbor_project_repo_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quota usage by project",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (project_name) (harbor_project_quota_usage_byte{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Members by project",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(project_name) (harbor_project_member_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Project Quta Usage ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " 100- ((harbor_project_quota_usage_byte {role=\"$Role\"}/ harbor_project_quota_byte{role=\"$Role\"}) * 100)and harbor_project_quota_byte {role=\"$Role\"} > 0\r\n",
     "legendFormat": "{{{{project_name}}}}"
    }
   ]
  },
  {
   "title": "Storage Safetly SLI ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(((harbor_project_quota_usage_byte{role=\"$Role\"} / on(project_name) harbor_project_quota_byte{role=\"$Role\"}) * 100) * on(project_name) group_left()(harbor_project_quota_byte{role=\"$Role\"} > 0)) < bool 90",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Artifacts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Total artifacts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(harbor_project_artifact_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Artifacts by Project",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(project_name) (harbor_project_artifact_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Artifacts by project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 39 },
   "targets": [
    {
     "expr": "sum by (project_name)(harbor_project_artifact_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Artifacts pulled by project",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(project_name) (harbor_artifact_pulled{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Artifacts pulled by project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum by(project_name) (harbor_artifact_pulled{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}