# Warning.yaml 

apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: microservice-warning-alert-rules
  namespace: monitoring
spec:
  groups:
    - name: Microservice-warning-alerts
      rules:
        - alert: HighRequestRateWarning
          expr: rate(vm_http_requests_total{namespace=~".*"}[5m]) > 0.7 * 1000
          for: 5m
          labels:
            severity: warning
            app: "{{ $labels.app }}"
            pod: "{{ $labels.pod }}"
          annotations:
            summary: "High request rate in pod {{ $labels.pod }} of app {{ $labels.app }}"
            description: "The request rate for pod {{ $labels.pod }} of app {{ $labels.app }} exceeded 70% of the expected rate for more than 5 minutes."

        - alert: HighErrorRateWarning
          expr: rate(vm_request_errors_total{namespace=~".*"}[5m]) > 0.01 * rate(vm_requests_total[5m])
          for: 5m
          labels:
            severity: warning
            app: "{{ $labels.app }}"
            pod: "{{ $labels.pod }}"
          annotations:
            summary: "High error rate in pod {{ $labels.pod }} of app {{ $labels.app }}"
            description: "The error rate for pod {{ $labels.pod }} of app {{ $labels.app }} exceeded 1% of total requests for more than 5 minutes."

        - alert: HighCPUUsageWarning
          expr: rate(container_cpu_usage_seconds_total{namespace=~".*"}[5m]) > 0.7 * 4
          for: 5m
          labels:
            severity: warning
            app: "{{ $labels.app }}"
            pod: "{{ $labels.pod }}"
          annotations:
            summary: "High CPU usage in pod {{ $labels.pod }} of app {{ $labels.app }}"
            description: "Pod {{ $labels.pod }} of app {{ $labels.app }} has CPU usage exceeding 70% of its limit for more than 5 minutes."

        - alert: HighMemoryUsageWarning
          expr: container_memory_working_set_bytes{namespace=~".*"} > 0.7 * 8e9
          for: 5m
          labels:
            severity: warning
            app: "{{ $labels.app }}"
            pod: "{{ $labels.pod }}"
          annotations:
            summary: "High memory usage in pod {{ $labels.pod }} of app {{ $labels.app }}"
            description: "Pod {{ $labels.pod }} of app {{ $labels.app }} has memory usage exceeding 70% of its limit for more than 5 minutes."




# Critical 

apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: microservice-critical-alert-rules
  namespace: monitoring
spec:
  groups:
    - name: Microservice-critical-alerts
      rules:
        - alert: HighRequestRateCritical
          expr: rate(vm_http_requests_total{namespace=~".*"}[5m]) > 0.9 * 1000
          for: 2m
          labels:
            severity: critical
            app: "{{ $labels.app }}"
            pod: "{{ $labels.pod }}"
          annotations:
            summary: "Critical: High request rate in pod {{ $labels.pod }} of app {{ $labels.app }}"
            description: "The request rate for pod {{ $labels.pod }} of app {{ $labels.app }} exceeded 90% of the expected rate for more than 2 minutes."

        - alert: HighErrorRateCritical
          expr: rate(vm_request_errors_total{namespace=~".*"}[5m]) > 0.05 * rate(vm_requests_total[5m])
          for: 2m
          labels:
            severity: critical
            app: "{{ $labels.app }}"
            pod: "{{ $labels.pod }}"
          annotations:
            summary: "Critical: High error rate in pod {{ $labels.pod }} of app {{ $labels.app }}"
            description: "The error rate for pod {{ $labels.pod }} of app {{ $labels.app }} exceeded 5% of total requests for more than 2 minutes."

        - alert: HighCPUUsageCritical
          expr: rate(container_cpu_usage_seconds_total{namespace=~".*"}[5m]) > 0.85 * 4
          for: 2m
          labels:
            severity: critical
            app: "{{ $labels.app }}"
            pod: "{{ $labels.pod }}"
          annotations:
            summary: "Critical: High CPU usage in pod {{ $labels.pod }} of app {{ $labels.app }}"
            description: "Pod {{ $labels.pod }} of app {{ $labels.app }} has CPU usage exceeding 85% of its limit for more than 2 minutes."

        - alert: HighMemoryUsageCritical
          expr: container_memory_working_set_bytes{namespace=~".*"} > 0.85 * 8e9
          for: 2m
          labels:
            severity: critical
            app: "{{ $labels.app }}"
            pod: "{{ $labels.pod }}"
          annotations:
            summary: "Critical: High memory usage in pod {{ $labels.pod }} of app {{ $labels.app }}"
            description: "Pod {{ $labels.pod }} of app {{ $labels.app }} has memory usage exceeding 85% of its limit for more than 2 minutes."
