{
 "title": "OpsTree/Kubernetes / Views / Pods",
 "description": "This is a modern 'Pods View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": ".*" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{ cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", cluster=~\"$cluster\"}, pod)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "job",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", cluster=~\"$cluster\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Created by",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ created_by_kind }}: {{ created_by_name }}"
    }
   ]
  },
  {
   "title": "Running on",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Pod IP",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ pod_ip }}"
    }
   ]
  },
  {
   "title": "Priority Class",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", pod=\"$pod\", priority_class!=\"\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ priority_class }}"
    }
   ]
  },
  {
   "title": "QOS Class",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 7, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_status_qos_class{namespace=\"$namespace\", pod=\"$pod\", cluster=~\"$cluster\"} > 0",
     "legendFormat": "{{ qos_class }}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\", pod=\"$pod\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Last Terminated Exit Code",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_exitcode{namespace=\"$namespace\", pod=\"$pod\", cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total pod CPU Requests usage",
   "type": "gauge",
   "description": "Shows how much of the total requested CPU is currently being used",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster\"}[$__rate_interval])) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", resource=\"cpu\", job=~\"$job\", cluster=~\"$cluster\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Total pod CPU Limits usage",
   "type": "gauge",
   "description": "Shows how much of the total CPU limit is being used",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster\"}[$__rate_interval])) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", resource=\"cpu\", job=~\"$job\", cluster=~\"$cluster\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Total pod RAM Requests usage",
   "type": "gauge",
   "description": "Shows how much of the total requested memory (RAM) is used by pods",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster\"}) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", resource=\"memory\", job=~\"$job\", cluster=~\"$cluster\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Total pod RAM Limits usage",
   "type": "gauge",
   "description": "Shows how much of the total memory limit is being used",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster\"}) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", resource=\"memory\", job=~\"$job\", cluster=~\"$cluster\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Resources by container",
   "type": "table",
   "description": " This table gives CPU and memory info per container in the namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", resource=\"cpu\", job=~\"$job\", cluster=~\"$cluster\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", resource=\"cpu\", job=~\"$job\", cluster=~\"$cluster\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", resource=\"memory\", job=~\"$job\", cluster=~\"$cluster\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", resource=\"memory\", job=~\"$job\", cluster=~\"$cluster\"}) by (container)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", cluster=~\"$cluster\"}[$__rate_interval])) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", cluster=~\"$cluster\"}) by (container)"
    }
   ]
  },
  {
   "title": "CPU Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster\"}[$__rate_interval])) by (container) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", resource=\"cpu\", job=~\"$job\", cluster=~\"$cluster\"}) by (container)",
     "legendFormat": "{{ container }}  REQUESTS"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster\"}[$__rate_interval])) by (container) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", resource=\"cpu\", job=~\"$job\", cluster=~\"$cluster\"}) by (container)",
     "legendFormat": "{{ container }}  LIMITS"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster\"}) by (container) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", resource=\"memory\", job=~\"$job\", cluster=~\"$cluster\"}) by (container)",
     "legendFormat": "{{ container }} REQUESTS"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster\"}) by (container) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", resource=\"memory\", job=~\"$job\", cluster=~\"$cluster\"}) by (container)",
     "legendFormat": "{{ container }} LIMITS"
    }
   ]
  },
  {
   "title": "CPU Usage by container",
   "type": "timeseries",
   "description": "Shows how much CPU each container is using. Helps identify high CPU consumers.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", cluster=~\"$cluster\"}[$__rate_interval])) by (container, id)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage by container",
   "type": "timeseries",
   "description": "Displays the memory (RAM) used by each container. Useful for spotting memory-hungry containers.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", cluster=~\"$cluster\"}) by (container, id)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU Throttled seconds by container",
   "type": "timeseries",
   "description": "Shows how much time containers were blocked from using CPU due to hitting limits. High throttling means performance issues.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", cluster=~\"$cluster\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "OOM Events by container",
   "type": "timeseries",
   "description": "Shows which containers faced an \"Out of Memory\" (OOM) error.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(container_oom_events_total{ container!=\"\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "description": "Displays how many times each container has restarted in the selected time range. Frequent restarts can indicate app crashes or configuration issues.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{ container!=\"\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Network - Bandwidth",
   "type": "timeseries",
   "description": "Shows the amount of network traffic (in MiB/s) received and transmitted by the containers. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network - Packets Rate",
   "type": "timeseries",
   "description": "Displays the number of network packets sent and received per second (packets/sec). Useful for analyzing network load.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network - Packets Dropped",
   "type": "timeseries",
   "description": "Shows how many packets were dropped during sending or receiving. High values can indicate network problems or resource limits.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network - Errors",
   "type": "timeseries",
   "description": "Displays the number of network-related errors while sending or receiving data. Ideally, this should always stay at zero.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{namespace=\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_errors_total{namespace=\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  }
 ]
}