{
 "title": "Opstree/Middleware/Redis",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x, it works with helm stable/redis-ha exporter.\r\n\r\nIf you missing redis memory utilization, please modify \"maxmemory\" value in values.yaml",
 "tags": [
  "redis",
  "ot-dashboard"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "gauge",
   "description": "Measures how long the Redis pod has been running.\t",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_uptime_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Slaves_Connected",
   "type": "stat",
   "description": "Measures how long the Redis pod has been running.\t",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_slaves_connected", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Replication Lag P1",
   "type": "timeseries",
   "description": "Represents the current replication offset, which is the total number of bytes sent by the primary to all replicas.",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "redis_replication_offset_bytes", "legendFormat": "__auto" }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Clients_connected",
   "type": "stat",
   "description": "Monitors the number of connected clients to Redis.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_clients_connected", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rejected-Connection",
   "type": "stat",
   "description": "Tracks connections rejected due to max clients or resource issues.\t",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(redis_connections_rejected_total)[5m]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis_DB_Keys/Expires",
   "type": "gauge",
   "description": "redis_db_keys:  How many total keys are stored in a Redis database.\nredis_db_expires:  How many of those keys have an expiration time set (they’ll automatically be removed later).",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_db_keys", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB_Expires_keys_TTL",
   "type": "stat",
   "description": "The average time-to-live (TTL) of keys set to expire in Redis.",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_db_avg_ttl_milliseconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Keys",
   "type": "bargauge",
   "description": "Tracks the number of keys that have expired in Redis./ Indicates the number of keys evicted due to memory constraints.\t",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_keys_expired_total", "legendFormat": "__auto" },
    { "expr": "redis_keys_evicted_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory_Usage",
   "type": "timeseries",
   "description": "Measures the memory usage by Redis in bytes.\t",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "__auto" },
    { "expr": "redis_memory_peak_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total_Memory_Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "__auto" },
    { "expr": "redis_memory_peak_bytes", "legendFormat": "__auto" },
    { "expr": "redis_memory_rss_bytes", "legendFormat": "__auto" },
    { "expr": "redis_memory_lua_bytes", "legendFormat": "__auto" },
    {
     "expr": "redis_memory_fragmentation_ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU_Usage",
   "type": "gauge",
   "description": "CPU usage by Redis.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_cpu_time_seconds_total", "legendFormat": "{{state}}" }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "clients_blocked",
   "type": "stat",
   "description": "Number of blocked clients waiting for operations to complete.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_clients_blocked", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Keyspace Hits / Misses per Sec ",
   "type": "gauge",
   "description": "Measures the number of successful key lookups in Redis./ Measures the number of failed key lookups in Redis.\t",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commands Executed  ",
   "type": "gauge",
   "description": "Tracks the total commands executed by Redis per sec.\t",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_commands_per_second", "legendFormat": "command" }
   ]
  },
  {
   "title": "Total_Commands_Executed",
   "type": "timeseries",
   "description": "Tracks the total commands executed by Redis.\t",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 27 },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total[5m])",
     "legendFormat": "cmd_executed"
    }
   ]
  },
  { "title": "General Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Network I/O P3",
   "type": "timeseries",
   "description": "Rate of incoming and outgoing network traffic.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(redis_clients_max_input_buffer_bytes[5m])",
     "legendFormat": "I/O"
    },
    {}
   ]
  },
  {
   "title": "Client I/O Buffer ",
   "type": "timeseries",
   "description": "Rate of incoming and outgoing network traffic.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(redis_clients_max_output_buffer_bytes[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}