{
 "title": "Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "business_unit",
    "label": "Business Unit",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total{org=\"coe\"},bu)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Services",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, service_name) (rate(traces_span_metrics_duration_milliseconds_bucket{span_kind=\"SPAN_KIND_SERVER\",bu=~\"$business_unit\",org=\"coe\"}[5m])))",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "(sum(rate(traces_span_metrics_duration_milliseconds_count{http_status_code!~\"^2.*|^3.*|^4.*\",BU=~\"$business_unit\",org=\"coe\"}[5m])) by (service_name)) / (sum(rate(traces_span_metrics_duration_milliseconds_count{BU=~\"$business_unit\",org=\"coe\",http_status_code!=\"\"}[5m])) by (service_name)) * 100",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "Loadbalancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Loadbalancer SLO",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route) (rate(kong_request_latency_ms_bucket{route=\"httproute.orchestrator.orchestrator-backend-api.1.0\"}[5m])))",
     "legendFormat": "{{route}}"
    },
    {
     "expr": "sum(rate(kong_http_requests_total{code=~\"^5.*\",route=\"httproute.orchestrator.orchestrator-backend-api.1.0\"}[5m])) by (route) / (sum(rate(kong_http_requests_total{route=\"httproute.orchestrator.orchestrator-backend-api.1.0\"}[5m])) by (route)) * 100",
     "legendFormat": "{{route}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Database SLO",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(ClickHouseProfileEvents_Query[15m])) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(ClickHouseMetrics_HTTPConnection) by (job) + sum(ClickHouseMetrics_TCPConnection) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(rate(ClickHouseMetrics_MemoryTracking[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Middleware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Kafka SLO",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_fetch_latency_avg[15m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(kafka_consumer_records_lag[15m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(kafka_consumer_rebalance_total) by (instance) /sum(kafka_consumer_rebalance_total) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}