#-- github repo: https://github.com/bitnami/charts/tree/main/bitnami/clickhouse

---
apiVersion: v2
name: clickhouse
description: A Helm chart for ClickHouse monitoring
type: application
version: 0.1.0
appVersion: 25.7.5
dependencies:
  - name: clickhouse
    alias: clickhouse
    version: 9.4.4
    repository: https://charts.bitnami.com/bitnami
