{
 "title": "MySql",
 "tags": [
  "ot-mysql",
  "ot-kit"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "account", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  { "title": "Overview & Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "This panel displays the total time, in seconds, that the MySQL server has been running since its last restart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_uptime_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "description": " This panel shows the total number of active client connections or threads currently connected to the MySQL server.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_threads\r\n", "legendFormat": "{{kind}}" }
   ]
  },
  { "title": "InnoDB Buffer Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Buffer Pool Operations Per Second",
   "type": "gauge",
   "description": "This graph shows operations  hitting the InnoDB Buffer Pool per second. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_buffer_pool_operations_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Buffer Pool Limit",
   "type": "timeseries",
   "description": "This panel shows the maximum configured size of the InnoDB Buffer Pool. Comparing this with 'Buffer Pool Usage' helps determine how much of the allocated memory is actually being utilized.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mysql_buffer_pool_limit_bytes\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Buffer Pool Usage",
   "type": "stat",
   "description": "This panel displays the amount of memory currently used by the InnoDB Buffer Pool. This reflects the working set of your data and indexes that are actively cached in memory.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_buffer_pool_usage_bytes", "legendFormat": "{{status}}" }
   ]
  },
  { "title": " Operations & Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total Commands Processed Per Second",
   "type": "timeseries",
   "description": " This graph displays the total rate of all commands (like SELECT, INSERT, UPDATE, DELETE) processed by the MySQL server per second. It provides an overall view of the database workload.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cmd/sec" } },
   "targets": [
    {
     "expr": "sum by (command) (rate(mysql_operations_total[5m]))",
     "legendFormat": "Operations_total"
    }
   ]
  },
  {
   "title": "Handler Operations ",
   "type": "timeseries",
   "description": " This graph shows the rate of various low-level handler operations (e.g., handler_read_rnd_next, handler_update) that InnoDB performs on tables. These indicate how frequently MySQL accesses rows and indexes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(mysql_handlers_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Locking ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Total Locks",
   "type": "timeseries",
   "description": "This graph shows the rate of all types of locks acquired by the MySQL server per second. A high rate doesn't necessarily indicate a problem, but it's important to correlate with 'Contention Rate'",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": " locks/sec" } },
   "targets": [
    {
     "expr": "sum by (lock_type) (rate(mysql_locks_total[5m]))",
     "legendFormat": "lock_total"
    }
   ]
  },
  {
   "title": "Row Locks ",
   "type": "timeseries",
   "description": " This graph specifically shows the rate at which transactions are waiting to acquire row-level locks. Frequent or long row lock waits are a strong indicator of concurrency issues, hot spots in your database, or inefficient transaction management in your application.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "wait/sec" } },
   "targets": [
    {
     "expr": "rate(mysql_row_locks_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk & Temporary Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Double Writes Per Second",
   "type": "timeseries",
   "description": "This graph shows the rate of \"double writes\" per second. InnoDB uses a doublewrite buffer as a recovery mechanism to ensure data integrity during crashes. A high rate is normal for busy systems, but it represents additional I/O overhead",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(mysql_double_writes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Opened Files/Tables",
   "type": "timeseries",
   "description": "This graph shows the rate at which MySQL is opening new file descriptors, tables, or sockets. A continuously high or increasing rate can indicate that table_open_cache or open_files_limit might need tuning, or that your application is frequently opening and closing connections/tables.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": " resources/sec" } },
   "targets": [
    {
     "expr": "sum by (resource_type) (rate(mysql_opened_resources_total[5m]))",
     "legendFormat": "opened_resources"
    }
   ]
  }
 ]
}