apiVersion: v2
name: otel-demo-app
description: A helm chart to install OTel Demo applicaiton 
type: application
version: 0.0.1
appVersion: 2.1.3

dependencies:
  - alias: otel-demo
    name: opentelemetry-demo
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.38.6
    tags:
      - otel-demo
