grafana:
  image:
    tag: "12.4.0-19913286788-ubuntu"
  grafana.ini:
    auth.azuread:
      enabled: true
      name: Azure AD
      client_id: "${GRAFANA_AZUREAD_CLIENT_ID}"
      client_secret: "${GRAFANA_AZUREAD_CLIENT_SECRET}"
      scopes: "openid email profile"
      auth_url: "https://login.microsoftonline.com/${GRAFANA_AZUREAD_TENANT_ID}/oauth2/v2.0/authorize"
      token_url: "https://login.microsoftonline.com/${GRAFANA_AZUREAD_TENANT_ID}/oauth2/v2.0/token"
      # allowed_groups: "Azure AD Group ID 1,Azure AD Group ID 2" 
      # role_attribute_path: "contains(groups[*], 'YOUR_GRAFANA_ADMIN_GROUP_ID') && 'Admin' || contains(groups[*], 'YOUR_GRAFANA_EDITOR_GROUP_ID') && 'Editor' || 'Viewer'"
      org_mapping:
         - "588a3265-a1c8-4031-a508-0b527f63de77:1:Admin"
         - "709da048-0023-4666-968e-e3bf5b0c8935:1:Editor"
         - "588a3265-a1c8-4031-a508-0b527f63de77:2:Admin"
         - "709da048-0023-4666-968e-e3bf5b0c8935:2:Editor"
      allowed_domains: "opstree.com mygurukulam.co"
    server:
      domain: grafana.opstree.net
      root_url: https://%(domain)s/
    feature_toggles:
      provisioning: "true"
      kubernetesDashboards: "true"
    users:
      default_theme: light

  envValueFrom:
    GRAFANA_AZUREAD_CLIENT_ID:
      secretKeyRef:
        name: grafana-azure-ad-creds
        key: client-id
    GRAFANA_AZUREAD_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-azure-ad-creds
        key: client-secret
    GRAFANA_AZUREAD_TENANT_ID:
      secretKeyRef:
        name: grafana-azure-ad-creds
        key: tenant-id

  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"

  # resources:
  #   requests:
  #     cpu: 1
  #     memory: 1Gi
  #   limits:
  #     cpu: 1
  #     memory: 1Gi

  plugins: 
    - grafana-polystat-panel
    - grafana-clickhouse-datasource 

  # ingress:
  #   enabled: true
  #   ingressClassName: nginx
  #   annotations: {}
  #     # konghq.com/strip-path: "true"  # Optional if Kong needs it
  #     # kubernetes.io/tls-acme: "true" # Uncomment if using cert-manager
  #   labels: {}
  #   hosts:
  #     - grafana.k8s.opstree.dev
  #   path: /
  #   pathType: Prefix

  persistence:
    enabled: true
    type: sts
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    finalizers:
      - kubernetes.io/pvc-protection
  tolerations:
    - key: "team"
      operator: "Equal"
      value: "o11y"
      effect: "NoSchedule"
  # nodeSelector:
  #   node-role.kubernetes.io/o11y: o11y

  testFramework:
    enabled: false
