{
 "title": "AWS CloudWatch Cost Analytics",
 "tags": [
  "aws ",
  "cost",
  "analytics"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClickHouse", "query": "grafana-clickhouse-datasource" },
   {
    "name": "account_name",
    "label": "Account Name",
    "query": "SELECT DISTINCT \n  account_name as __text,\n  account_name as __value\nFROM cost.service_costs \nWHERE account_name IS NOT NULL\nORDER BY account_name;"
   }
  ]
 },
 "panels": [
  {
   "title": "Daily CloudWatch Cost Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  toDate(usage_start_ts) AS date,\n  round(sum(cost_blended), 2) AS total_cloudwatch_cost,\n  min(usage_start_ts) as min_ts,\n  max(usage_start_ts) as max_ts\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\nGROUP BY date\nORDER BY date\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS S3 Cost Analytics, user=1 */\nSELECT\n  toDate(usage_start_ts) AS date,\n  round(sum(cost_blended), 2) AS total_cloudwatch_cost,\n  min(usage_start_ts) as min_ts,\n  max(usage_start_ts) as max_ts\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\nGROUP BY date\nORDER BY date",
     "rawSql": "SELECT\n  toDate(usage_start_ts) AS time,\n  account_name AS metric,\n  SUM(cost_blended) AS _\nFROM cost.service_costs\nWHERE\n  $__timeFilter(usage_start_ts)\n  AND product_code = 'AmazonCloudWatch'\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY\n  time,\n  metric\nORDER BY\n  time",
     "round": "0s"
    }
   ]
  },
  {
   "title": "High-Level Cost View ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Account ID",
     "type": "piechart",
     "description": "CloudWatch cost on the basis of account ids",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    concat('Account ID -', cast(account_id AS String)) AS metric,\n    round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n",
       "rawQuery": "/* grafana dashboard=AWS CloudWatch Cost Analytics, user=1 */\nSELECT\n    concat('Account ID -', cast(account_id AS String)) AS metric,\n    round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\nGROUP BY metric\nORDER BY value DESC",
       "rawSql": "SELECT\n  concat('Account Name: ', account_name) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY account_name, metric\nORDER BY value DESC",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Region",
     "type": "piechart",
     "description": "Cost Comparison Across Regions",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  region AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\nGROUP BY region\nORDER BY value DESC\n\n",
       "rawQuery": "/* grafana dashboard=AWS RDS Cost Analytics, user=1 */\nSELECT\n  region AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\nGROUP BY region\nORDER BY value DESC",
       "rawSql": "SELECT   \n  region AS metric,   \n  round(sum(cost_blended), 2) AS value \nFROM cost.service_costs \nWHERE product_code = 'AmazonCloudWatch'   \n  AND $__timeFilter(usage_start_ts)   \n  AND account_name IS NOT NULL\n  AND (     \n    'All' IN (${account_name}) OR account_name IN (${account_name})   \n  ) \nGROUP BY region \nORDER BY value DESC",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Availability Zones",
     "type": "piechart",
     "description": "CloudWatch cost on the basis of Availability Zones",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  availability_zone AS metric,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND trimBoth(availability_zone) != ''\nGROUP BY metric\nORDER BY total_cost DESC\n\n\n\n",
       "rawQuery": "/* grafana dashboard=AWS CloudWatch Cost Analytics, user=1 */\nSELECT\n  availability_zone AS metric,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND trimBoth(availability_zone) != ''\nGROUP BY metric\nORDER BY total_cost DESC",
       "rawSql": "SELECT\n  availability_zone AS metric,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND trimBoth(availability_zone) != ''\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY metric\nORDER BY total_cost DESC",
       "round": "0s"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation & Usage Cost Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operation-Wise",
     "type": "piechart",
     "description": "CloudWatch cost on the basis of Operation-Wise",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "dateTimeColDataType": "usage_start_ts",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  trim(instance_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND instance_family IS NOT NULL\n  AND trim(instance_family) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
       "rawQuery": "/* grafana dashboard=AWS CloudWatch Cost Analytics, user=1 */\nSELECT\n  trim(instance_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND instance_family IS NOT NULL\n  AND trim(instance_family) != ''\nGROUP BY metric\nORDER BY value DESC",
       "rawSql": "SELECT      \n  operation,     \n  SUM(usage_qty) AS total_gb_mo \nFROM cost.service_costs \nWHERE product_code = 'AmazonCloudWatch'   \n  AND $__timeFilter(usage_start_ts)   \n  AND account_name IS NOT NULL\n  AND (     \n    'All' IN (${account_name}) OR account_name IN (${account_name})   \n  ) \nGROUP BY operation \nORDER BY total_gb_mo DESC",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Storage Usage by Log Group (GB-Mo)",
     "type": "piechart",
     "description": "CloudWatch cost on the basis of Storage Usage by Log Group (GB-Mo)",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "dateTimeColDataType": "usage_start_ts",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  trim(instance_type_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND instance_type_family IS NOT NULL\n  AND trim(instance_type_family) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
       "rawQuery": "/* grafana dashboard=AWS CloudWatch Cost Analytics, user=1 */\nSELECT\n  trim(instance_type_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND instance_type_family IS NOT NULL\n  AND trim(instance_type_family) != ''\nGROUP BY metric\nORDER BY value DESC",
       "rawSql": "SELECT \n    resource_id AS log_group,\n    SUM(usage_qty) AS total_gb_mo\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND operation = 'HourlyStorageMetering'\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY log_group\nORDER BY total_gb_mo DESC",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Storage Usage by EKS Cluster Name",
     "type": "piechart",
     "description": "EC2 cost on the basis of Storage Usage by EKS Cluster Name",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "dateTimeColDataType": "usage_start_ts",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  trim(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND instance_type IS NOT NULL\n  AND trim(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
       "rawQuery": "/* grafana dashboard=AWS CloudWatch Cost Analytics, user=1 */\nSELECT\n  trim(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND instance_type IS NOT NULL\n  AND trim(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
       "rawSql": "SELECT \n    splitByString('/', resource_id)[5] AS eks_cluster_name,\n    SUM(usage_qty) AS total_gb_mo\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND operation = 'HourlyStorageMetering'\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY eks_cluster_name\nORDER BY total_gb_mo DESC",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Pricing Model",
     "type": "piechart",
     "description": "CloudWatch cost on the basis of Pricing Model ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "dateTimeColDataType": "usage_start_ts",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  trim(pricing_model) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND trim(pricing_model) != ''\n  AND pricing_model IS NOT NULL\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
       "rawQuery": "/* grafana dashboard=AWS RDS Cost Analytics, user=1 */\nSELECT\n  trim(pricing_model) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND trim(pricing_model) != ''\n  AND pricing_model IS NOT NULL\nGROUP BY metric\nORDER BY value DESC",
       "rawSql": "SELECT   \n  trim(pricing_model) AS metric,   \n  round(sum(cost_blended), 2) AS value \nFROM cost.service_costs \nWHERE product_code = 'AmazonCloudWatch'   \n  AND pricing_model IS NOT NULL   \n  AND trim(pricing_model) != ''   \n  AND $__timeFilter(usage_start_ts)   \n  AND account_name IS NOT NULL\n  AND (     \n    'All' IN (${account_name}) OR account_name IN (${account_name})   \n  ) \nGROUP BY metric \nORDER BY value DESC",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Storage Usage by Pricing Unit",
     "type": "piechart",
     "description": "CloudWatch Instance Cost on Basis of Storage Usage by Pricing Unit",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "dateTimeColDataType": "usage_start_ts",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND trimBoth(pricing_model) = 'Spot'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n\n",
       "rawQuery": "/* grafana dashboard=AWS CloudWatch Cost Analytics, user=1 */\nSELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND trimBoth(pricing_model) = 'Spot'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
       "rawSql": "SELECT \n    pricing_unit,\n    SUM(usage_qty) AS total_usage\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY pricing_unit\nORDER BY total_usage DESC",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Storage Usage by Resource Type (Log Group Prefix)",
     "type": "piechart",
     "description": "CloudWatch Instance Cost on Basis of Storage Usage by Resource Type (Log Group Prefix)",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "dateTimeColDataType": "usage_start_ts",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND trimBoth(pricing_model) = 'OnDemand'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n",
       "rawQuery": "/* grafana dashboard=AWS CloudWatch Cost Analytics, user=1 */\nSELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND trimBoth(pricing_model) = 'OnDemand'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
       "rawSql": "SELECT \n    splitByString('/', resource_id)[4] AS log_group_prefix,\n    SUM(usage_qty) AS total_gb_mo\nFROM cost.service_costs\nWHERE product_code = 'AmazonCloudWatch'\n  AND operation = 'HourlyStorageMetering'\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY log_group_prefix\nORDER BY total_gb_mo DESC",
       "round": "0s"
      }
     ]
    }
   ]
  }
 ]
}