{
 "title": "SRE At A Glance",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "## Frontend\n#### 1 Week\n**SLI:** Availability | **SLO:** 99.50%\n<br>\n**SLI:** Latency [100ms] | **SLO:** 99.00%\n<br>\n**SLI:** Success Rate | **SLO:** 99.00%\n"
   }
  },
  {
   "title": "Availability SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"frontend\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"frontend\"}[7d:1m]\n  )\n  * 100,\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (round(\n  (\n    clamp_min(\n      ( 0.995 - \n        (count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"frontend\"} > 0)[7d:1m]) \n        / \n        count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"frontend\"}[7d:1m]))\n      ) * 100, 0 \n      )\n    / 0.005\n  ),\n  0.01\n))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Latency SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"200\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.99 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"frontend\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"100\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"frontend\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.01\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Success Rate SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.99 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"frontend\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"frontend\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.01\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": {
    "content": "## Cart\n#### 1 Week\n**SLI:** Availability | **SLO:** 99.90%\n<br>\n**SLI:** Latency [50ms] | **SLO:** 99.00%\n<br>\n**SLI:** Success Rate | **SLO:** 99.50%\n"
   }
  },
  {
   "title": "Availability SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"cart\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"cart\"}[7d:1m]\n  )\n  * 100,\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"cart\"} > 0)[7d:1m]) \n        / \n        count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"cart\"}[7d:1m]))\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Latency SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"100\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.99 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"cart\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"50\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"cart\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.01\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Success Rate SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.995 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"cart\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"cart\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.005\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": {
    "content": "## Checkout\n#### 1 Week\n**SLI:** Availability | **SLO:** 99.90%\n<br>\n**SLI:** Latency [1000ms] | **SLO:** 99.00%\n<br>\n**SLI:** Success Rate | **SLO:** 99.50%\n"
   }
  },
  {
   "title": "Availability SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"checkout\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"checkout\"}[7d:1m]\n  )\n  * 100,\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"checkout\"} > 0)[7d:1m]) \n        / \n        count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"checkout\"}[7d:1m]))\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Latency SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"1000\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.99 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"checkout\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"1000\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"checkout\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.01\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Success Rate SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.995 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"checkout\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"checkout\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.005\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "options": {
    "content": "## Payment\n#### 1 Week\n**SLI:** Availability | **SLO:** 99.90%\n<br>\n**SLI:** Latency [50ms] | **SLO:** 99.90%\n<br>\n**SLI:** Success Rate | **SLO:** 99.99%\n"
   }
  },
  {
   "title": "Availability SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"payment\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"payment\"}[7d:1m]\n  )\n  * 100,\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"payment\"} > 0)[7d:1m]) \n        / \n        count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"payment\"}[7d:1m]))\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Latency SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"50\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"payment\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"50\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"payment\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Success Rate SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.9999 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"payment\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"payment\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.0001\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "options": {
    "content": "## Ads\n#### 1 Week\n**SLI:** Availability | **SLO:** 99.90%\n<br>\n**SLI:** Latency [100ms] | **SLO:** 99.50%\n<br>\n**SLI:** Success Rate | **SLO:** 99.90%\n"
   }
  },
  {
   "title": "Availability SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"ad\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"ad\"}[7d:1m]\n  )\n  * 100,\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"ad\"} > 0)[7d:1m]) \n        / \n        count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"ad\"}[7d:1m]))\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Latency SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"100\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.995 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"ad\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"100\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"ad\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.005\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Success SLO",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate Error Budget",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.9999 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"ad\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"ad\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.0001\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}