{
 "title": "SRE In Depth",
 "description": "SRE Quantified",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "title": "Frontend Web", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"frontend\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"frontend\"}[7d:1m]\n  )\n  * 100,\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\r\n  (\r\n    0.995 -\r\n    (\r\n      count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"frontend\"} > 0)[$__range:1m])\r\n      /\r\n      count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"frontend\"}[$__range:1m])\r\n    )\r\n  ) / 0.005 * ($__range_s / 3600),\r\n0)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\r\n  50.4 -\r\n  (\r\n    (\r\n      0.995 -\r\n      (\r\n        count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"frontend\"} > 0)[7d:1m])\r\n        /\r\n        count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"frontend\"}[7d:1m])\r\n      )\r\n    ) / 0.005 * 50.4\r\n  ),\r\n0)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI - Availability | SLO - 99.50% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"frontend\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"frontend\"}[7d:1m]\n  )\n  * 100,\n  0.01\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "SLI - Availability | SLO - 99.90% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"frontend\"} > 0)[1h:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"frontend\"}[1h:1m]\n  )\n  * 100,\n  0.01\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "Latency SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"200\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    clamp_min(\n      ( 0.99 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"frontend\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"100\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"frontend\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.01\n  ),\n  0.01\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.99 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"frontend\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"100\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"frontend\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.01\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "SLI - Latency [100ms] | SLO - 99.00% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"200\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.01\n)",
     "legendFormat": "1-Week % Requests Under 400ms"
    }
   ]
  },
  {
   "title": "SLI - Latency [100ms] | SLO - 99.00% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"200\"\n  }[5m]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[5m])),\n  0.0001\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "Success SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    clamp_min(\n      ( 0.99 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"frontend\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"frontend\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.01\n  ),\n  0.01\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.99 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"frontend\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"frontend\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.01\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Success Rate | SLO - 99.50% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 13 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "1-Week % Requests Under 400ms"
    }
   ]
  },
  {
   "title": "Success Rate | SLO - 99.50% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 13 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[5m]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"frontend\",\n    span_kind=\"SPAN_KIND_SERVER\",\n  }[5m])),\n  0.0001\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  { "title": "Cart", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Availability SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"cart\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"cart\"}[7d:1m]\n  )\n  * 100,\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"cart\"} > 0)[7d:1m]) \n        / \n        count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"cart\"}[7d:1m]))\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"cart\"} > 0)[7d:1m]) \n        / \n        count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"cart\"}[7d:1m]))\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "SLI - Availability | SLO - 99.90% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 20 },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"cart\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"cart\"}[7d:1m]\n  )\n  * 100,\n  0.01\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "SLI - Availability | SLO - 99.90% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 20 },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"cart\"} > 0)[1h:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"cart\"}[1h:1m]\n  )\n  * 100,\n  0.01\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "Latency SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"100\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    clamp_min(\n      ( 0.99 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"cart\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"50\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"cart\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.01\n  ),\n  0.01\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.99 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"cart\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"50\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"cart\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.01\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "SLI - Latency [50ms] | SLO - 99.00% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 26 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"100\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.01\n)",
     "legendFormat": "1-Week % Requests Under 400ms"
    }
   ]
  },
  {
   "title": "SLI - Latency [50ms] | SLO - 99.00% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 26 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"100\"\n  }[5m]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[5m])),\n  0.0001\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "Success SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    clamp_min(\n      ( 0.995 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"cart\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"cart\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.005\n  ),\n  0.01\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.995 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"cart\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"cart\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.005\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Success Rate | SLO - 99.50% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 32 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "1-Week % Requests Under 400ms"
    }
   ]
  },
  {
   "title": "Success Rate | SLO - 99.50% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 32 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[5m]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"cart\",\n    span_kind=\"SPAN_KIND_SERVER\",\n  }[5m])),\n  0.0001\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  { "title": "Checkout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Availability SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"checkout\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"checkout\"}[7d:1m]\n  )\n  * 100,\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"checkout\"} > 0)[7d:1m]) \n        / \n        count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"checkout\"}[7d:1m]))\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"checkout\"} > 0)[7d:1m]) \n        / \n        count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"checkout\"}[7d:1m]))\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "SLI - Availability | SLO - 99.90% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 39 },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"checkout\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"checkout\"}[7d:1m]\n  )\n  * 100,\n  0.01\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "SLI - Availability | SLO - 99.90% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 39 },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"checkout\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"checkout\"}[7d:1m]\n  )\n  * 100,\n  0.01\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "Latency SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"1000\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    clamp_min(\n      ( 0.99 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"checkout\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"1000\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"checkout\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.01\n  ),\n  0.01\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.99 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"checkout\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"1000\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"checkout\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.01\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "SLI - Latency [1000ms] | SLO - 99.00% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 45 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"1000\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.01\n)",
     "legendFormat": "1-Week % Requests Under 400ms"
    }
   ]
  },
  {
   "title": "SLI - Latency [1000ms] | SLO - 99.00% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 45 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"1000\"\n  }[5m]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[5m])),\n  0.0001\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "Success SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    clamp_min(\n      ( 0.995 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"checkout\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"checkout\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.005\n  ),\n  0.01\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.995 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"checkout\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"checkout\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.005\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Success Rate | SLO - 99.50% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 51 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "1-Week % Requests Under 400ms"
    }
   ]
  },
  {
   "title": "Success Rate | SLO - 99.50% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 51 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[5m]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"checkout\",\n    span_kind=\"SPAN_KIND_SERVER\",\n  }[5m])),\n  0.0001\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  { "title": "Payment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Availability SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"payment\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"payment\"}[7d:1m]\n  )\n  * 100,\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"payment\"} > 0)[7d:1m]) \n        / \n        count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"payment\"}[7d:1m]))\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"payment\"} > 0)[7d:1m]) \n        / \n        count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"payment\"}[7d:1m]))\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "SLI - Availability | SLO - 99.90% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 58 },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"payment\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"payment\"}[7d:1m]\n  )\n  * 100,\n  0.01\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "SLI - Availability | SLO - 99.90% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 58 },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"payment\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"payment\"}[7d:1m]\n  )\n  * 100,\n  0.01\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "Latency SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"50\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"payment\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"50\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"payment\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"payment\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"50\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"payment\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "SLI - Latency [50ms] | SLO - 99.90% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 64 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"50\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.01\n)",
     "legendFormat": "1-Week % Requests Under 400ms"
    }
   ]
  },
  {
   "title": "SLI - Latency [50ms] | SLO - 99.90% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 64 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"50\"\n  }[5m]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[5m])),\n  0.0001\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "Success SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    clamp_min(\n      ( 0.9999 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"payment\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"payment\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.0001\n  ),\n  0.01\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.9999 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"payment\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"payment\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.0001\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Success Rate | SLO - 99.99% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 70 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "1-Week % Requests Under 400ms"
    }
   ]
  },
  {
   "title": "Success Rate | SLO - 99.99% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 70 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[5m]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"payment\",\n    span_kind=\"SPAN_KIND_SERVER\",\n  }[5m])),\n  0.0001\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  { "title": "Ads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Availability SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"ad\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"ad\"}[7d:1m]\n  )\n  * 100,\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"ad\"} > 0)[7d:1m]) \n        / \n        count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"ad\"}[7d:1m]))\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.999 - \n        (count_over_time((kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"ad\"} > 0)[7d:1m]) \n        / \n        count_over_time(kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"ad\"}[7d:1m]))\n      ) * 100, 0 \n      )\n    / 0.001\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "SLI - Availability | SLO - 99.90% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 77 },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"ad\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"ad\"}[7d:1m]\n  )\n  * 100,\n  0.01\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "SLI - Availability | SLO - 99.90% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 77 },
   "targets": [
    {
     "expr": "round(\n  count_over_time(\n    (kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"ad\"} > 0)[7d:1m]\n  )\n  /\n  count_over_time(\n    kube_deployment_status_replicas_ready{namespace=\"otel-demo\", deployment=\"ad\"}[7d:1m]\n  )\n  * 100,\n  0.01\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "Latency SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"100\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    clamp_min(\n      ( 0.995 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"ad\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"100\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"ad\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.005\n  ),\n  0.01\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.995 - \n        (\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"ad\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"100\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n          service_name=\"ad\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          le=\"+Inf\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.005\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "SLI - Latency [100ms] | SLO - 99.50% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 83 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"100\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[7d])),\n  0.01\n)",
     "legendFormat": "1-Week % Requests Under 400ms"
    }
   ]
  },
  {
   "title": "SLI - Latency [100ms] | SLO - 99.90% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 83 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"100\"\n  }[5m]))\n  /\n  sum(rate(traces_span_metrics_duration_milliseconds_bucket{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    le=\"+Inf\"\n  }[5m])),\n  0.0001\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  },
  {
   "title": "Success SLO % | 1 Week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  (\n    clamp_min(\n      ( 0.9999 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"ad\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"ad\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.0001\n  ),\n  0.01\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  round(\n  (\n    clamp_min(\n      ( 0.9999 - (\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"ad\",\n          span_kind=\"SPAN_KIND_SERVER\",\n          status_code!=\"STATUS_CODE_ERROR\"\n        }[7d:1m]))\n        /\n        sum(rate(traces_span_metrics_calls_total{\n          service_name=\"ad\",\n          span_kind=\"SPAN_KIND_SERVER\"\n        }[7d:1m]))\n      )\n      ) * 100, 0 \n      )\n    / 0.0001\n  ),\n  0.01\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Success Rate | SLO - 99.90% | 1 Week",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 89 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[7d]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\"\n  }[7d])),\n  0.0001\n)",
     "legendFormat": "1-Week % Requests Under 400ms"
    }
   ]
  },
  {
   "title": "Success Rate | SLO - 99.90% | Real Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 89 },
   "targets": [
    {
     "expr": "round(\n  100 *\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\",\n    status_code!=\"STATUS_CODE_ERROR\"\n  }[5m]))\n  /\n  sum(rate(traces_span_metrics_calls_total{\n    service_name=\"ad\",\n    span_kind=\"SPAN_KIND_SERVER\",\n  }[5m])),\n  0.0001\n)",
     "legendFormat": "Real-Time % request under 400ms"
    }
   ]
  }
 ]
}