{
 "title": "MSSQL windows_exporter",
 "description": "Performance and health metrics for your SQL Servers using windows Exporter v0.16 and Prometheus",
 "tags": [
  "SQL Server",
  "Prometheus",
  "windows_exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "60s" },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(windows_mssql_collector_duration_seconds, job)"
   },
   {
    "name": "dbinstance",
    "label": "DB Instance",
    "query": "label_values(windows_mssql_genstats_logical_connections, mssql_instance)"
   }
  ]
 },
 "panels": [
  { "title": "SRV | General Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DATABASES HEALTH",
   "type": "stat",
   "description": "Shows Databse Health ",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$server.*\"}"
    }
   ]
  },
  {
   "title": "LOGICAL CONNECTIONS",
   "type": "stat",
   "description": "**LOGICAL CONNECTIONS**\n\nNumber of logical connections to the system.\n\nThe main purpose of logical connections is to service multiple active result sets (MARS) requests. For MARS requests, every time that an application makes a connection to SQL Server, there may be more than one logical connection that corresponds to a physical connection.\n\nWhen MARS is not used, the ratio between physical and logical connections is 1:1. Therefore, every time that an application makes a connection to SQL Server, logical connections will increase by 1.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_logical_connections{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "NETWORK UTILIZATION",
   "type": "stat",
   "description": "Shows the real-time network utilization percentage based on incoming and outgoing traffic across all network interfaces.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(irate(windows_net_bytes_total{job=~\"$server.*\"}[5m]))) \r\n/ \r\n125000000 * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STORAGE",
   "type": "gauge",
   "description": "**STORAGE**\n\nShow drive space usage by percentage.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(({__name__=~\"^windows_logical_disk_size_bytes.*\", job=~\"$server.*\"} - {__name__=~\"^windows_logical_disk_free_bytes.*\", job=~\"$server.*\"}) / {__name__=~\"^windows_logical_disk_size_bytes.*\", job=~\"$server.*\"} * 100, \"name\", \"$1\", \"__name__\", \"(.*)\")",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "ACTIVE TEMP TABLES",
   "type": "stat",
   "description": "Shows the number of active temporary tables currently in use by the SQL Server instance",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_active_temp_tables{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "tempDB FREE SPACE",
   "type": "stat",
   "description": "Shows the amount of free space available in TempDB",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_transactions_tempdb_free_space_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "LOGINS-LOGOUTS",
   "type": "bargauge",
   "description": "**LOGINS-LOGOUTS**\n\nTotal number of logins started per second. This does not include pooled connections.\n\nTotal number of logout operations started per second.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate (windows_mssql_genstats_logins{mssql_instance=~\"$dbinstance.*\"}[1m])",
     "legendFormat": "Logins/m"
    },
    {
     "expr": "rate (windows_mssql_genstats_logouts{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}[1m])",
     "legendFormat": "Logins/m"
    }
   ]
  },
  {
   "title": "LOCK WAITS I/O",
   "type": "stat",
   "description": "**LOCK WAITS I/O**\n\nSQL Trace IO Provider Lock Waits",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_sql_trace_io_provider_lock_waits{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "DEADLOCKS",
   "type": "stat",
   "description": "**DEADLOCKS**\n\nNumber of lock requests per second that resulted in a deadlock since last restart",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_mars_deadlocks{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "RUIG",
   "type": "stat",
   "description": "\nNumber of duplicate tempdb recovery unit id generated.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_tempdb_recovery_unit_ids_generated{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "CONNECTIONS RESETS",
   "type": "stat",
   "description": "Shows the number of SQL Server connection resets",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_connection_resets{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "LONGEST TRANSACT RUN",
   "type": "stat",
   "description": "Shows the duration in seconds of the longest-running active transaction on the SQL Server instance. ",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_transactions_longest_transaction_running_seconds{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  { "title": "KPI | CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "**CPU Usage**\n\nShow cpu usage by mode.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (irate(windows_cpu_time_total{job=~\"$server.*\"}[$interval]))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "**CPU**\n\nShow CPU usage by percentage.",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$server.*\", mode=~\"idle.*\"}[$interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPU load per process",
   "type": "timeseries",
   "description": "**CPU load per process**\n\nShow cpu usage by process.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (process) (rate(process_cpu_seconds_total {job=~\"$server.*\", process !~\"Idle\"}[$interval]))",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  {
   "title": "USER CONNECTIONS",
   "type": "stat",
   "description": "**USER CONNECTIONS**\n\nCounts the number of users currently connected to SQL Server.",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_mssql_genstats_user_connections{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  { "title": "KPI | Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Target Server Memory",
   "type": "stat",
   "description": "Shows SQL Server Target Server Memory, which is the amount of RAM SQL Server",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_memmgr_target_server_memory_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "Buffer Pool Rate",
   "type": "stat",
   "description": "Shows the number of times SQL Server located the required data page in the Buffer Cache \n(memory) instead of reading it from disk",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_bufman_buffer_cache_hits{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "PAGE WRITES",
   "type": "stat",
   "description": "Shows the number of data pages SQL Server writes from the Buffer Pool to disk",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_bufman_page_writes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "DATA FILE SIZE",
   "type": "stat",
   "description": "Shows the total size of all SQL Server data files (.mdf and .ndf) for the selected instance. ",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mssql_instance) (windows_mssql_databases_data_files_size_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})"
    }
   ]
  },
  {
   "title": "PLE",
   "type": "stat",
   "description": "**PLE**\n\nIndicates the number of seconds a page will stay in the buffer pool without references.",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_bufman_page_life_expectancy_seconds{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "BYTES PER CONNECTION",
   "type": "stat",
   "description": "Shows the total memory used by active SQL Server connections. This includes session context, \nlogin information, user session data, and internal connection structures.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mssql_instance) (windows_mssql_memmgr_connection_memory_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})"
    }
   ]
  },
  {
   "title": "SQL Actual Memory Usage",
   "type": "stat",
   "description": "Shows the total amount of memory currently in use by SQL Server",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_memmgr_total_server_memory_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "Free List Stalls/sec",
   "type": "stat",
   "description": "Shows the number of times SQL Server could not find a free buffer page and had to wait",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_bufman_free_list_stalls{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "PAGE READS",
   "type": "stat",
   "description": "Shows the number of data pages SQL Server is reading from disk into the Buffer Pool",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_bufman_page_reads{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "LOG USED (%)",
   "type": "stat",
   "description": "Shows the average percentage of transaction log space used across all databases in the \nselected SQL Server instance",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_log_used_percent{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})"
    }
   ]
  },
  {
   "title": "Memory Grant Pending",
   "type": "stat",
   "description": "Shows the number of SQL queries waiting for a memory grant",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_memmgr_pending_memory_grants{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  {
   "title": "SQL Stolen Memory",
   "type": "stat",
   "description": "Shows the amount of memory SQL Server has taken (\"stolen\") from the buffer pool for \ninternal operations such as query execution, sorting, hashing, index",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_mssql_memmgr_stolen_server_memory_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}"
    }
   ]
  },
  { "title": "Performance Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "SQL Server Activity",
   "type": "timeseries",
   "description": "Shows the number of SQL batches processed per second by the SQL Server instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_mssql_sqlstats_batch_requests{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Batch Requests/sec"
    },
    {
     "expr": "windows_mssql_genstats_user_connections{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "User Connections"
    },
    {
     "expr": "windows_mssql_genstats_logins{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Logins/sec"
    },
    {
     "expr": "windows_mssql_genstats_logouts{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Logouts/sec"
    },
    {
     "expr": "windows_mssql_sqlstats_sql_compilations{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "SQL Compilations/sec"
    },
    {
     "expr": "windows_mssql_sqlstats_sql_recompilations{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "SQL Re-Compilations/sec"
    },
    {
     "expr": "windows_mssql_genstats_blocked_processes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Processes blocked"
    }
   ]
  },
  {
   "title": "DB Transactions – Average",
   "type": "timeseries",
   "description": "Shows the average number of SQL transactions occurring across all databases in the \nselected SQL Server instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_transactions{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Transactions/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_write_transactions{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Write Transactions/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_log_flushes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Flushes/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_log_flush_wait_seconds{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Log Flush Wait Time"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_locks_lock_timeouts{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Lock Timeouts/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_group_commit_stall_seconds{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Group Stall/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_locks_lock_wait_seconds{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Lock Waits/sec"
    },
    {
     "expr": "avg by (mssql_instance) (windows_mssql_databases_log_pool_disk_reads{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
     "legendFormat": "Pool Disc/sec"
    }
   ]
  },
  {
   "title": "Full Scans/sec",
   "type": "timeseries",
   "description": "Shows the number of full table or full index scans performed by SQL Server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_mssql_accessmethods_full_scans{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Full Scans/sec"
    },
    {
     "expr": "windows_mssql_accessmethods_index_searches{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Index Searches/sec"
    },
    {
     "expr": "windows_mssql_accessmethods_page_splits{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Page Splits/sec"
    },
    {
     "expr": "windows_mssql_bufman_page_lookups{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Page lookups/sec"
    },
    {
     "expr": "windows_mssql_bufman_page_reads{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Page reads/sec"
    },
    {
     "expr": "windows_mssql_bufman_page_writes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Page writes/sec"
    },
    {
     "expr": "windows_mssql_bufman_read_ahead_pages{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Readahead pages/sec"
    },
    {
     "expr": "windows_mssql_bufman_lazywrites{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Lazy writes/sec"
    },
    {
     "expr": "windows_mssql_bufman_checkpoint_pages{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Checkpoint pages/sec"
    }
   ]
  },
  {
   "title": "SQL Cache Memory",
   "type": "timeseries",
   "description": "Shows the amount of memory SQL Server is using to store cached SQL objects, including \nquery execution plans, stored procedure plans, ad-hoc plans, and prepared statements. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "windows_mssql_memmgr_sql_cache_memory_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "SQL Cache"
    },
    {
     "expr": "windows_mssql_memmgr_optimizer_memory_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Optimizer"
    },
    {
     "expr": "windows_mssql_memmgr_log_pool_memory_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Log Pool"
    },
    {
     "expr": "windows_mssql_memmgr_lock_memory_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Lock"
    },
    {
     "expr": "windows_mssql_memmgr_database_cache_memory_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Database Cache"
    },
    {
     "expr": "windows_mssql_memmgr_connection_memory_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}",
     "legendFormat": "Connection"
    }
   ]
  },
  {
   "title": "Lock Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"windows_mssql_locks_lock_requests.*\",job=~\"$server.*\"}, \"name\", \"$1\", \"__name__\", \"windows_mssql_locks_lock_requests(.*)\")",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Ratios",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_mssql_accessmethods_page_splits{job=~\"$server.*\"}",
     "legendFormat": "Pages split/batch request"
    },
    {
     "expr": "windows_mssql_sqlstats_sql_compilations{job=~\"$server.*\"}",
     "legendFormat": "SQL Compilation/batch request"
    },
    {
     "expr": "windows_mssql_bufman_page_reads{job=~\"$server.*\"}",
     "legendFormat": "Read-ahead/page read"
    },
    {
     "expr": "windows_mssql_sqlstats_sql_recompilations{job=~\"$server.*\"}",
     "legendFormat": "SQL Recompilation/batch request"
    }
   ]
  },
  {
   "title": "Database Size Trend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database | Rows Size",
     "type": "timeseries",
     "description": "Shows the number of rows inserted using Bulk Copy operations (BCP, Bulk Insert, SSIS, SqlBulkCopy, ETL jobs) for each SQL Server database.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_mssql_databases_bulk_copy_rows.*\", job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Database | Log Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_mssql_databases_log_files_size_bytes.*\", job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ database }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Latency | FETCH/PEAK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch | DLC Latency (ms)",
     "type": "timeseries",
     "description": "**Fetch | DLC Latency (ms)**\n\nAverage latency in microseconds between log blocks entering the Direct Log Consumer and being retrieved by the XTP controller, per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_mssql_databases_xtp_controller_dlc_fetch_latency_seconds.*\", job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Peak | DLC Latency (ms)",
     "type": "timeseries",
     "description": "**Peak | DLC Latency (ms)**\n\nThe largest recorded latency, in microseconds, of a fetch from the Direct Log Consumer by the XTP controller.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_mssql_databases_xtp_controller_dlc_peak_latency_seconds.*\", job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ database }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log | Pool Activities",
     "type": "timeseries",
     "description": "Shows the number of log cache misses in SQL Server. \nA cache miss occurs when required log data is not found in memory and must be fetched from disk. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_cache_misses{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Cache Misses/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_disk_reads{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Disk Reads/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_empty_free_pool_pushes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Empty Free Pool Pushes/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_hash_deletes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Hash Deletes/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_hash_inserts{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Hash Inserts/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_log_scan_pushes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Log Scan Pushes/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_requests{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Requests/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_requests_old_vlf{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Requests Old VLF/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_total_active_log_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_pool_total_shared_pool_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Pool Total Shared Pool Bytes/sec"
      }
     ]
    },
    {
     "title": "Log | Bytes",
     "type": "timeseries",
     "description": "Displays SQL Server transaction log activity including log file size, used size, \nflush operations, bytes written, and wait times.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_files_size_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Files Size Bytes/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_files_used_size_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Files Used Size Bytes/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flush_wait_seconds{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Flush Wait Seconds/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flush_waits{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Flush Waits/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flush_write_seconds{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Flush Write Seconds/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flushed_bytes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Flushed Bytes/sec"
      },
      {
       "expr": "sum by (mssql_instance) (windows_mssql_databases_log_flushes{job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"})",
       "legendFormat": "Log Flushes/sec"
      }
     ]
    },
    {
     "title": "Database | Log Used",
     "type": "timeseries",
     "description": "Shows the percentage of transaction log space used for each SQL Server database.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_mssql_databases_log_used_percent.*\", job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}, \"db\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ database }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Lock Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lock Wait Time",
     "type": "timeseries",
     "description": "Shows the time SQL Server queries spend waiting on locks, broken down by lock type. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace({__name__=\"windows_mssql_locks_lock_wait_seconds\", job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}, \"name\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ resource }}"
      }
     ]
    },
    {
     "title": "Lock Timeouts",
     "type": "timeseries",
     "description": "Shows SQL Server lock timeouts by lock type. \nA lock timeout occurs when a query cannot acquire a lock within the configured wait period \nand SQL Server cancels the operation",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "label_replace({__name__=\"windows_mssql_locks_lock_timeouts\", job=~\"$server.*\", mssql_instance=~\"$dbinstance.*\"}, \"name\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ resource }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used space",
     "type": "timeseries",
     "description": "Shows the total amount of disk space currently consumed on each logical disk/partition",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"^windows_logical_disk_size_bytes.*\", job=~\"$server.*\"} - {__name__=~\"^windows_logical_disk_free_bytes.*\", job=~\"$server.*\"}, \"name\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ volume }}"
      }
     ]
    },
    {
     "title": "Available Space",
     "type": "timeseries",
     "description": "Shows the amount of free storage available on each logical disk/partition. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"windows_logical_disk_free_bytes.*\",job=~\"$server.*\"}, \"name\", \"$1\", \"__name__\", \"(.*)\")",
       "legendFormat": "{{ volume }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "**Network Traffic**\n\nHere we can see how much network traffic is generated by the Server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(windows_net_bytes_received_total{job=~\"$server\"}[$interval]) or irate(windows_net_bytes_received_total{job=~\"$server\"}[5m])",
       "legendFormat": "Inbound"
      },
      {
       "expr": "rate(windows_net_bytes_sent_total{job=~\"$server\"}[$interval]) or irate(windows_net_bytes_sent_total{job=~\"$server\"}[5m])",
       "legendFormat": "Outbound"
      }
     ]
    },
    {
     "title": "Network Usage Hourly",
     "type": "timeseries",
     "description": "**Network Usage Hourly**\n\nHere we can see how much network traffic is generated by the Server per hour.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "increase(windows_net_bytes_received_total{job=~\"$server\"}[1h])",
       "legendFormat": "Received"
      },
      {
       "expr": "increase(windows_net_bytes_sent_total{job=~\"$server\"}[1h])",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  }
 ]
}