apiVersion: v2
name: kafka-exporter
description: A Helm chart for prometheus-community/kafka_exporter
type: application
dependencies:
  - name: prometheus-kafka-exporter
    alias: kafka-exporter
    version: 2.15.0
    repository: https://prometheus-community.github.io/helm-charts
version: 0.1.0
appVersion: v1.9.0
