{
 "title": "Anomalies - Adaptive",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "anomaly_name",
    "query": {
     "query": "label_values({job=\"$job\"},anomaly_name)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"$job\", anomaly_name=\"$anomaly_name\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Baselines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Baselines",
   "type": "timeseries",
   "description": "Baselines provide upper and lower bands around time series data to identify anomalies. Values that remain outside the bands for significant periods of time will be identified as anomalies.",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "anomaly:adaptive:select{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}",
     "legendFormat": "{{anomaly_name}}"
    },
    {
     "expr": "last_over_time(anomaly:lower_band{job=\"$job\", anomaly_name=\"$anomaly_name\", anomaly_strategy=\"adaptive\", instance=~\"$instance\"}[2m])",
     "legendFormat": "anomaly_lower_band"
    },
    {
     "expr": "last_over_time(anomaly:upper_band{job=\"$job\", anomaly_name=\"$anomaly_name\", anomaly_strategy=\"adaptive\", instance=~\"$instance\"}[2m])",
     "legendFormat": "anomaly_upper_band"
    },
    {
     "expr": "ALERTS{job=\"$job\", anomaly_name=\"$anomaly_name\", anomaly_strategy=\"adaptive\", instance=~\"$instance\", alertstate=\"firing\", anomaly_select=\"1\"}",
     "legendFormat": "anomalies"
    }
   ]
  },
  {
   "title": "Constants",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anomaly:adaptive:stddev_multiplier",
     "legendFormat": "stddev_multiplier"
    },
    {
     "expr": "anomaly:adaptive:margin_multiplier",
     "legendFormat": "margin_multiplier"
    },
    {
     "expr": "anomaly:adaptive:threshold_by_covar",
     "legendFormat": "threshold_by_covar"
    },
    {
     "expr": "anomaly:adaptive:sparse_threshold",
     "legendFormat": "sparse_threshold"
    }
   ]
  },
  { "title": "Explanation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "1. Mid-line (avg over 1h)",
   "type": "timeseries",
   "description": "The mid-line is calculated using a moving average over a 1 hour time window. It follows the trend while removing noise. Baselines are defined above and below the mid-line.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "anomaly:adaptive:select{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}",
     "legendFormat": "{{anomaly_name}}"
    },
    {
     "expr": "anomaly:adaptive:avg_1h{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}",
     "legendFormat": "avg_1h"
    }
   ]
  },
  {
   "title": "2. Stddev over 1h + High Pass Filter",
   "type": "timeseries",
   "description": "The standard deviation over a 1 hour time window is used as the basis for calculating the width of the upper and lower bands. A high pass filter is applied to remove periods of low variability. The high pass filter uses the coefficient of variation to define a threshold that  is applicable to any time series (as the threshold depends on the magnitude of the time series's values). The high pass filter has the effect of increasing the sensitivity of the bands and improving their overall stability.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "anomaly:adaptive:select{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}",
     "legendFormat": "{{anomaly_name}}"
    },
    {
     "expr": "anomaly:adaptive:stddev_1h:filtered{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}",
     "legendFormat": "stddev_1h_filtered"
    }
   ]
  },
  {
   "title": "3. Smooth over 26h",
   "type": "timeseries",
   "description": "The filtered standard deviation over a 1 hour time window is smoothed over a 26 hour period using a moving average. This creates stable and robust bands that adapt to increased variability in a controlled way, especially in the presence of spikes.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "anomaly:adaptive:select{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}",
     "legendFormat": "{{anomaly_name}}"
    },
    {
     "expr": "anomaly:adaptive:stddev_st{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}",
     "legendFormat": "stddev_1h_over_26h"
    }
   ]
  },
  {
   "title": "4. Short term bands",
   "type": "timeseries",
   "description": "The smoothed filtered standard deviation is used to calculate the final short term upper and lower bands. This is done by scaling it by a certain factor and adding it to (or subtracting it from) the mid-line.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "anomaly:adaptive:select{job=\"$job\", anomaly_name=\"$anomaly_name\"}",
     "legendFormat": "{{anomaly_name}}"
    },
    {
     "expr": "last_over_time(anomaly:adaptive:avg_1h{job=\"$job\", anomaly_name=\"$anomaly_name\"}[2m]) + last_over_time(anomaly:adaptive:stddev_st{job=\"$job\", anomaly_name=\"$anomaly_name\"}[2m]) * on() group_left anomaly:adaptive:stddev_multiplier",
     "legendFormat": "short_term_upper_band"
    },
    {
     "expr": "last_over_time(anomaly:adaptive:avg_1h{job=\"$job\", anomaly_name=\"$anomaly_name\"}[2m]) - last_over_time(anomaly:adaptive:stddev_st{job=\"$job\", anomaly_name=\"$anomaly_name\"}[2m]) * on() group_left anomaly:adaptive:stddev_multiplier",
     "legendFormat": "short_term_lower_band"
    }
   ]
  },
  {
   "title": "5. Margin bands",
   "type": "timeseries",
   "description": "Margin bands complement short term bands in situations where short term bands are very narrow or do not exist at all (have been removed by the high pass filter). This can happen when the time series presents very low variability. They are purely based on the moving average over 1 hour, scaled by a certain factor.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "anomaly:adaptive:select{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}",
     "legendFormat": "{{anomaly_name}}"
    },
    {
     "expr": "last_over_time(anomaly:adaptive:avg_1h{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}[2m]) - last_over_time(anomaly:adaptive:avg_1h{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}[2m]) * on() group_left anomaly:adaptive:margin_multiplier",
     "legendFormat": "margin_lower_band"
    },
    {
     "expr": "last_over_time(anomaly:adaptive:avg_1h{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}[2m]) + last_over_time(anomaly:adaptive:avg_1h{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}[2m]) * on() group_left anomaly:adaptive:margin_multiplier",
     "legendFormat": "margin_upper_band"
    }
   ]
  },
  {
   "title": "6. Seasonality",
   "type": "timeseries",
   "description": "Seasonality uses past data to detect long term patterns and prevent recurrent events from triggering false positives. Their calculation is similar to the short term bands, but with an offset (1 day, 1 week).",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "anomaly:adaptive:select{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}",
     "legendFormat": "{{anomaly_name}}"
    },
    {
     "expr": "max(last_over_time(anomaly:adaptive:upper_band_lt{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}[10m])) by (anomaly_name)",
     "legendFormat": "long_term_upper_band"
    },
    {
     "expr": "min(last_over_time(anomaly:adaptive:lower_band_lt{job=\"$job\", anomaly_name=\"$anomaly_name\", instance=~\"$instance\"}[10m])) by (anomaly_name)",
     "legendFormat": "long_term_lower_band"
    }
   ]
  }
 ]
}