{
 "title": "Grafana Faro - Frontend Monitoring",
 "description": "Frontend monitoring dashboard using metrics collected with Grafana Faro SDK.",
 "tags": [
  "grafana",
  "faro",
  "frontend"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {}
   },
   {
    "name": "app",
    "label": "Application",
    "query": {}
   },
   { "name": "datasource", "label": "datasource", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time to First Byte (TTFB)",
   "type": "stat",
   "description": "TTFB is a metric that measures the time between the request for a resource and when the first byte of a response begins to arrive.\nhttps://web.dev/ttfb/",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({deployment_environment=\"$env\",service_name=\"$app\"} | kind = \"measurement\" |= \"ttfb\" | logfmt | unwrap ttfb [$__range]) by (service_name)  ",
     "legendFormat": "TTFB"
    }
   ]
  },
  {
   "title": "First Contentful Paint (FCP)",
   "type": "stat",
   "description": "The First Contentful Paint (FCP) metric measures the time from when the page starts loading to when any part of the page's content is rendered on the screen. For this metric, \"content\" refers to text, images (including background images), <svg> elements, or non-white <canvas> elements.\nhttps://web.dev/fcp/",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({deployment_environment=\"$env\",service_name=\"$app\"} | kind=\"measurement\" |= \" fcp=\" | logfmt | unwrap fcp [$__range]) by (service_name)",
     "legendFormat": "FCP"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "stat",
   "description": "Cumulative Layout Shift (CLS): measures visual stability. To provide a good user experience, pages should maintain a CLS of 0.1. or less.\nhttps://web.dev/cls/",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({service_name=\"$app\", deployment_environment=\"$env\"} | kind = `measurement`  |= \"cls\" | logfmt | unwrap cls [$__range]) by (service_name)",
     "legendFormat": "CLS"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP)",
   "type": "stat",
   "description": "Largest Contentful Paint (LCP): measures loading performance. To provide a good user experience, LCP should occur within 2.5 seconds of when the page first starts loading.\nhttps://web.dev/lcp/",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({service_name=\"$app\", deployment_environment=\"$env\"} | kind=\"measurement\" |= \" lcp=\" | logfmt | unwrap lcp [$__range]) by (Application)",
     "legendFormat": "LCP"
    }
   ]
  },
  {
   "title": "First Input Delay (FID)",
   "type": "stat",
   "description": "First Input Delay (FID): measures interactivity. To provide a good user experience, pages should have a FID of 100 milliseconds or less.\nhttps://web.dev/fid/",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({service_name=\"$app\", deployment_environment=\"$env\"} | kind=\"measurement\" |= \" fid=\" | logfmt | unwrap fid [$__range]) by (Application)",
     "legendFormat": "FID"
    }
   ]
  },
  {
   "title": "Page Load, p75",
   "type": "timeseries",
   "description": "TTFB is a metric that measures the time between the request for a resource and when the first byte of a response begins to arrive.\nhttps://web.dev/ttfb/",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {service_name=\"$app\", deployment_environment=\"$env\"} | kind=\"measurement\" |= \" ttfb=\" | logfmt | unwrap ttfb [5m]) by (Application)",
     "legendFormat": "TTFB"
    },
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",Environment=\"$env\",Application=\"$app\"} |= \" fcp=\" | logfmt | unwrap fcp [5m]) by (app)",
     "legendFormat": "FCP"
    },
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",Environment=\"$env\",Application=\"$app\"} |= \" lcp=\" | logfmt | unwrap lcp [5m]) by (app)",
     "legendFormat": "LCP"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift, p75",
   "type": "timeseries",
   "description": "Cumulative Layout Shift (CLS): measures visual stability. To provide a good user experience, pages should maintain a CLS of 0.1. or less.\nhttps://web.dev/cls/",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {service_name=\"$app\", deployment_environment=\"$env\"} | kind=\"measurement\" |= \" cls=\" | logfmt | unwrap cls [5m]) by (Application)",
     "legendFormat": "CLS"
    }
   ]
  },
  {
   "title": "First Input Delay, p75",
   "type": "timeseries",
   "description": "First Input Delay (FID): measures interactivity. To provide a good user experience, pages should have a FID of 100 milliseconds or less.\nhttps://web.dev/fid/",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.75, {service_name=\"$app\", deployment_environment=\"$env\"} | kind=\"measurement\" |= \" fid=\" | logfmt | unwrap fid [5m]) by (Application)",
     "legendFormat": "FID"
    }
   ]
  },
  { "title": "Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"$app\", deployment_environment=\"$env\"} | kind=\"exception\" [$__range])) by (Application)"
    }
   ]
  },
  {
   "title": "Exceptions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(count_over_time({service_name=\"$app\", deployment_environment=\"$env\"} | kind=\"exception\" [$__interval])) by (service_name)",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Top Exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count(count_over_time({service_name=\"$app\", deployment_environment=\"$env\"} | kind=\"exception\" | logfmt [$__range])) by (value))"
    }
   ]
  },
  {
   "title": "Top URLs by Exception Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count(count_over_time( {service_name=\"$app\", deployment_environment=\"$env\"} | kind=\"exception\" | logfmt [$__range])) by (page_url))"
    }
   ]
  },
  {
   "title": "Top Browsers by Exception Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count by (browser_name, browser_version) (count_over_time({service_name=\"$app\", deployment_environment=\"$env\"} | kind=\"exception\" | logfmt [$__range])))"
    }
   ]
  },
  { "title": "Meta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Popular Browsers",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count(count_over_time({service_name=\"$app\", deployment_environment=\"$env\"} | kind=\"measurement\" |= \" ttfb=\" | logfmt [$__range])) by (browser_name, browser_version))"
    }
   ]
  },
  {
   "title": "Visits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"$app\", deployment_environment=\"$env\"} | kind=\"measurement\" |= \" ttfb=\" [$__interval])",
     "legendFormat": "visits"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Top Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count(count_over_time({service_name=\"$app\", deployment_environment=\"$env\"} | kind=\"event\" | logfmt [$__range])) by (event_name))"
    }
   ]
  },
  {
   "title": "Top Users",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(50, count(count_over_time({service_name=\"$app\", deployment_environment=\"$env\"} | kind=\"event\" | logfmt | event_name = \"mainspa_mount\" [$__range])) by (user_id))"
    }
   ]
  }
 ]
}