
postgres:
  global:
    postgresql:
      fullnameOverride: 
      auth:
        postgresPassword: "postgres"
        username: "otelu"
        password: "otelp"
        database: "otel"
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r4

  primary:
    persistence:
      enabled: true
      size: 1Gi
    extendedConfiguration: |-
      shared_preload_libraries = 'pg_stat_statements,auto_explain'
      # Optional: Further configure the extensions as needed
      pg_stat_statements.max = 10000
      pg_stat_statements.track = all
      auto_explain.log_min_duration = '250ms' # Log plans for queries slower than 250ms
      auto_explain.log_analyze = on
      auto_explain.log_buffers = on

    resources:
      requests:
        cpu: 1m
        memory: 2Mi
      limits:
        cpu: 500m
        memory: 512Mi