{
 "title": "AWS RDS Cost Analytics",
 "tags": [
  "aws ",
  "cost",
  "analytics"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClickHouse", "query": "grafana-clickhouse-datasource" },
   {
    "name": "account_name",
    "query": "SELECT DISTINCT \n  account_name as __text,\n  account_name as __value\nFROM cost.service_costs \nWHERE account_name IS NOT NULL\nORDER BY account_name;"
   }
  ]
 },
 "panels": [
  {
   "title": "Daily RDS Cost Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  toDate(usage_start_ts) AS date,\n  round(sum(cost_blended), 2) AS total_rds_cost,\n  min(usage_start_ts) as min_ts,\n  max(usage_start_ts) as max_ts\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\nGROUP BY date\nORDER BY date\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS RDS Cost Analytics, user=1 */\nSELECT\n  toDate(usage_start_ts) AS date,\n  round(sum(cost_blended), 2) AS total_rds_cost,\n  min(usage_start_ts) as min_ts,\n  max(usage_start_ts) as max_ts\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\nGROUP BY date\nORDER BY date",
     "rawSql": "SELECT\n  toDate(usage_start_ts) AS time,\n  account_name AS metric,\n  SUM(cost_blended) AS _\nFROM cost.service_costs\nWHERE\n  $__timeFilter(usage_start_ts)\n  AND product_code = 'AmazonRDS'\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY\n  time,\n  metric\nORDER BY\n  time\n\n",
     "round": "0s"
    }
   ]
  },
  { "title": "High-Level Cost View ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Account ID",
   "type": "piechart",
   "description": "RDS cost on the basis of account ids",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  account_id,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\nGROUP BY account_id\nORDER BY total_cost DESC\n\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS RDS Cost Analytics, user=1 */\nSELECT\n  account_id,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\nGROUP BY account_id\nORDER BY total_cost DESC",
     "rawSql": "SELECT\n  concat('Account Name : ', account_name) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\nAND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY account_name,metric\nORDER BY value DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Region",
   "type": "piechart",
   "description": "Cost Comparison Across Regions",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  region AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\nGROUP BY region\nORDER BY value DESC\n\n",
     "rawQuery": "/* grafana dashboard=AWS RDS Cost Analytics, user=1 */\nSELECT\n  region AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\nGROUP BY region\nORDER BY value DESC",
     "rawSql": "SELECT\n  region AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\nAND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY region\nORDER BY value DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Availability Zones",
   "type": "piechart",
   "description": "RDS cost on the basis of Availability Zones",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  availability_zone AS metric,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND trimBoth(availability_zone) != ''\nGROUP BY metric\nORDER BY total_cost DESC\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS RDS Cost Analytics, user=1 */\nSELECT\n  availability_zone AS metric,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND trimBoth(availability_zone) != ''\nGROUP BY metric\nORDER BY total_cost DESC",
     "rawSql": "SELECT\n  availability_zone AS metric,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND trimBoth(availability_zone) != ''\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY metric\nORDER BY total_cost DESC",
     "round": "0s"
    }
   ]
  },
  { "title": "Snapshot Cost Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": " Snapshot Resources by Cost",
   "type": "piechart",
   "description": "RDS cost on the basis of  Snapshot Resources ",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trim(instance_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND instance_family IS NOT NULL\n  AND trim(instance_family) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS RDS Cost Analytics, user=1 */\nSELECT\n  trim(instance_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND instance_family IS NOT NULL\n  AND trim(instance_family) != ''\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  resource_id,\n  ROUND(SUM(cost_blended), 5) AS total_snapshot_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND product_family ILIKE '%Snapshot%'\n  AND resource_id != ''\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY resource_id\nORDER BY total_snapshot_cost DESC\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Account-Wise RDS Snapshot Cost ",
   "type": "piechart",
   "description": "RDS cost on the basis of Instance Type Family",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trim(instance_type_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND instance_type_family IS NOT NULL\n  AND trim(instance_type_family) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS RDS Cost Analytics, user=1 */\nSELECT\n  trim(instance_type_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND instance_type_family IS NOT NULL\n  AND trim(instance_type_family) != ''\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  concat('Account Name : ', account_name ) AS metric,\n  ROUND(SUM(cost_blended), 5) AS total_snapshot_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND product_family ILIKE '%Snapshot%'\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY account_name, metric\nORDER BY total_snapshot_cost DESC\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Snapshot Cost by Usage Type (Region-Wise)",
   "type": "piechart",
   "description": "RDS cost on the basis Snapshot Cost by Usage Type (Region-Wise)",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trim(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND instance_type IS NOT NULL\n  AND trim(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS RDS Cost Analytics, user=1 */\nSELECT\n  trim(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND instance_type IS NOT NULL\n  AND trim(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  region,\n  usage_type,\n  ROUND(SUM(cost_blended), 5) AS snapshot_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND product_family ILIKE '%Snapshot%'\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY region, usage_type\nORDER BY snapshot_cost DESC\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Pricing Model",
   "type": "piechart",
   "description": "RDS cost on the basis of Pricing Model ",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trim(pricing_model) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND trim(pricing_model) != ''\n  AND pricing_model IS NOT NULL\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS RDS Cost Analytics, user=1 */\nSELECT\n  trim(pricing_model) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND trim(pricing_model) != ''\n  AND pricing_model IS NOT NULL\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  trim(pricing_model) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND trim(pricing_model) != ''\n  AND pricing_model IS NOT NULL\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY metric\nORDER BY value DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Aurora vs Standard RDS Snapshot Cost",
   "type": "piechart",
   "description": "RDS Instance Cost on Basis of Aurora vs Standard RDS Snapshot",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeColDataType": "usage_start_ts",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND trimBoth(pricing_model) = 'Spot'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS RDS Cost Analytics, user=1 */\nSELECT\n  trimBoth(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND trimBoth(pricing_model) = 'Spot'\n  AND trimBoth(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
     "rawSql": "SELECT\n  IF(usage_type ILIKE '%Aurora%', 'Aurora', 'Standard RDS') AS snapshot_type,\n  ROUND(SUM(cost_blended), 5) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonRDS'\n  AND product_family ILIKE '%Snapshot%'\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY snapshot_type\n",
     "round": "0s"
    }
   ]
  }
 ]
}