{
 "title": "Clickhouse Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Clickhouse overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_VersionInteger{job=\"coe-clickhouse\"}"
    },
    {
     "expr": "ClickHouseMetrics_Revision{job=\"coe-clickhouse\"}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_NumberOfTables{job=\"coe-clickhouse\"}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_Uptime{job=\"coe-clickhouse\"}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_NumberOfDatabases{job=\"coe-clickhouse\"}"
    },
    {
     "expr": "ClickHouseMetrics_ReadonlyReplica{job=\"coe-clickhouse\"}"
    },
    {
     "expr": "ClickHouseMetrics_KafkaConsumers{job=\"coe-clickhouse\"}"
    },
    {
     "expr": "(ClickHouseAsyncMetrics_OSMemoryTotal{job=\"coe-clickhouse\"}\n-\nClickHouseAsyncMetrics_OSMemoryFreePlusCached{job=\"coe-clickhouse\"})\n/ ClickHouseAsyncMetrics_OSMemoryTotal{job=\"coe-clickhouse\"} * 100"
    },
    {
     "expr": "(1 - ClickHouseAsyncMetrics_OSIdleTimeNormalized{job=\"coe-clickhouse\"}) * 100 "
    },
    {
     "expr": "ClickHouseAsyncMetrics_OSUptime{job=\"coe-clickhouse\"}"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "  label_replace(\n    {__name__=~\"ClickHouseAsyncMetrics_DiskAvailable_.*\", job=\"coe-clickhouse\"},\n    \"disk\", \"$1\", \"__name__\", \"ClickHouseAsyncMetrics_DiskAvailable_(.*)\"\n  )",
     "legendFormat": "{{disk}}"
    },
    {
     "expr": "  label_replace(\n    {__name__=~\"ClickHouseAsyncMetrics_DiskUsed_.*\", job=\"coe-clickhouse\"},\n    \"disk\", \"$1\", \"__name__\", \"ClickHouseAsyncMetrics_DiskUsed_(.*)\"\n  )",
     "legendFormat": "{{disk}}"
    },
    {
     "expr": "  label_replace(\n    {__name__=~\"ClickHouseAsyncMetrics_DiskTotal_.*\", job=\"coe-clickhouse\"},\n    \"disk\", \"$1\", \"__name__\", \"ClickHouseAsyncMetrics_DiskTotal_(.*)\"\n  )"
    },
    {
     "expr": "  label_replace(\n    {__name__=~\"ClickHouseAsyncMetrics_DiskUnreserved_.*\", job=\"coe-clickhouse\"},\n    \"disk\", \"$1\", \"__name__\", \"ClickHouseAsyncMetrics_DiskUnreserved_(.*)\"\n  )"
    },
    {
     "expr": "(\n  label_replace(\n    {__name__=~\"ClickHouseAsyncMetrics_DiskTotal_.*\", job=\"coe-clickhouse\"},\n    \"disk\", \"$1\", \"__name__\", \"ClickHouseAsyncMetrics_DiskTotal_(.*)\"\n  )\n  -\n  label_replace(\n    {__name__=~\"ClickHouseAsyncMetrics_DiskAvailable_.*\", job=\"coe-clickhouse\"},\n    \"disk\", \"$1\", \"__name__\", \"ClickHouseAsyncMetrics_DiskAvailable_(.*)\"\n  )\n)\n/\nlabel_replace(\n  {__name__=~\"ClickHouseAsyncMetrics_DiskTotal_.*\", job=\"coe-clickhouse\"},\n  \"disk\", \"$1\", \"__name__\", \"ClickHouseAsyncMetrics_DiskTotal_(.*)\"\n)\n* 100\n"
    }
   ]
  },
  {
   "title": "ClickHouse Service Memory Usage",
   "type": "timeseries",
   "description": "Total amount of memory (bytes) allocated by the server. This is the internal memory tracking by ClickHouse, instead of OS Level memory.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking{job=\"coe-clickhouse\"}",
     "legendFormat": "cli201-22a.cpp5.prod.clickhouse.com"
    }
   ]
  },
  {
   "title": "Clickhouse CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_OSIdleTimeNormalized{job=\"coe-clickhouse\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slow reads",
   "type": "timeseries",
   "description": "Number of reads from a file that were slow. This indicate system overload. Thresholds are controlled by read_backoff_* settings.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SlowRead{job=\"coe-clickhouse\"}[2m]))[$__rate_interval:15s] ) ",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SlowRead{job=\"coe-clickhouse\"}[$__rate_interval]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read backoff",
   "type": "timeseries",
   "description": "Number of times the number of query processing threads was lowered due to slow reads.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBackoff{job=\"coe-clickhouse\"}[2m]))[$__rate_interval:15s] ) ",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBackoff{job=\"coe-clickhouse\"}[$__rate_interval]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Parts of Merge Tree Tables",
   "type": "timeseries",
   "description": "Total Parts of MergeTreeTables. From the source code, we could see that this only refers to Active Parts",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_TotalPartsOfMergeTreeTables{job=\"coe-clickhouse\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "description": "Number of queries to be interpreted and potentially executed. Does not include queries that failed to parse or were rejected due to AST size limits, quota limits or limits on the number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_Query{job=\"coe-clickhouse\"}[2m])/120",
     "legendFormat": "peaks - {{instance}}"
    }
   ]
  },
  {
   "title": "Failed queries per Second",
   "type": "timeseries",
   "description": "Number of failed queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_FailedQuery{job=\"coe-clickhouse\"}[$__rate_interval]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queries Exceeded Memory Limit per Second",
   "type": "timeseries",
   "description": "Number of times when memory limit exceeded for query.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_QueryMemoryLimitExceeded{job=\"coe-clickhouse\"}[$__rate_interval]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Selected Rows per Second",
   "type": "timeseries",
   "description": "Number of rows SELECTed from all tables.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedRows{job=\"coe-clickhouse\"}[2m]))[$__rate_interval:15s] ) ",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SelectedRows{job=\"coe-clickhouse\"}[$__rate_interval]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Clickhouse Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{database=\"clickhouse\"} |= ``"
    }
   ]
  }
 ]
}