{
 "title": "MySql",
 "tags": [
  "ot-dashboard ",
  "mysql-db"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "ApplicationGroup",
    "label": "ApplicationGroup",
    "query": {
     "query": "label_values(mysql_global_status_uptime{rems_application_group!=\"REMS\"},rems_application_group)"
    }
   },
   {
    "name": "Service",
    "label": "Service",
    "query": {
     "query": "label_values(mysql_up{rems_application_group=\"$ApplicationGroup\"},rems_service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview & Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{rems_application_group=\"$ApplicationGroup\", rems_service=\"$Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Uptime",
   "type": "stat",
   "description": "MySQL Server Uptime - The time elapsed since the last restart of the MySQL server.",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{rems_application_group=\"$ApplicationGroup\", rems_service=\"$Service\"} /3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Connections",
   "type": "gauge",
   "description": "Number of client sessions currently connected to the MySQL server.",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_threads_connected{rems_application_group=\"$ApplicationGroup\", rems_service=\"$Service\", db_type=\"mysql\" }",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "description": "Current number of SQL queries executed per minute by the MySQL server.",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{rems_application_group=\"$ApplicationGroup\", rems_service=\"$Service\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Locking ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Immediate Locks",
     "type": "timeseries",
     "description": "Number of times MySQL acquired a table lock instantly without waiting.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": " locks/sec" } },
     "targets": [
      {
       "expr": "rate(mysql_global_status_table_locks_immediate{rems_application_group=\"$ApplicationGroup\", rems_service=\"$Service\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "waited   Locks ",
     "type": "timeseries",
     "description": "Number of times MySQL queries had to wait because the table was already locked.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "lock/sec" } },
     "targets": [
      {
       "expr": "rate(mysql_global_status_table_locks_waited{rems_application_group=\"$ApplicationGroup\", rems_service=\"$Service\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Slow Queries",
     "type": "timeseries",
     "description": "Total number of queries that exceeded 10 sec",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mysql_global_status_slow_queries{ rems_application_group=\"$ApplicationGroup\", rems_service=\"$Service\"}[$__rate_interval]))",
       "legendFormat": "Slow Queries"
      }
     ]
    },
    {
     "title": "MySQL Sorts",
     "type": "timeseries",
     "description": "**MySQL Sorts**\n\nDue to a query's structure, order, or other requirements, MySQL sorts the rows before returning them. For example, if a table is ordered 1 to 10 but you want the results reversed, MySQL then has to sort the rows to return 10 to 1.\n\nThis graph also shows when sorts had to scan a whole table or a given range of a table in order to return the results and which could not have been sorted via an index.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mysql_global_status_sort_rows{rems_application_group=\"$ApplicationGroup\", rems_service=\"$Service\"}[$__rate_interval]))",
       "legendFormat": "Sort Rows"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mysql_global_status_sort_range{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Sort Range"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mysql_global_status_sort_merge_passes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Sort Merge Passes"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mysql_global_status_sort_scan{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Sort Scan"
      }
     ]
    }
   ]
  },
  {
   "title": "Row Operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "row operation",
     "type": "timeseries",
     "description": "Number of rows read, inserted, updated, and deleted by the InnoDB storage engine.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(mysql_global_status_innodb_row_ops_total{rems_application_group=\"$ApplicationGroup\", rems_service=\"$Service\"}[$__rate_interval])) by (operation)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Temporary Objects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Temporary Objects",
     "type": "timeseries",
     "description": "Created Tmp Tables:\nNumber of temporary tables created in memory during query execution.\n\nCreated Tmp Disk Tables:\nNumber of temporary tables created on disk when memory limits are exceeded.\n\nCreated Tmp Files:\nNumber of temporary files created by MySQL for operations like sorting and joins during query execution.",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mysql_global_status_created_tmp_tables{rems_application_group=\"$ApplicationGroup\", rems_service=\"$Service\"}[$__rate_interval]))",
       "legendFormat": "Created Tmp Tables"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mysql_global_status_created_tmp_disk_tables{ instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "Created Tmp Disk Tables"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mysql_global_status_created_tmp_files{ instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "Created Tmp Files"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Memory allocated ",
     "type": "stat",
     "description": "Total memory allocated to the InnoDB buffer pool.\n\nThis is the memory MySQL uses to cache data pages and indexes instead of reading from disk",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(mysql_global_variables_innodb_buffer_pool_size {rems_application_group=\"$ApplicationGroup\", rems_service=\"$Service\"}/ 1024 / 1024)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consumed Buffer Pool Memory",
     "type": "stat",
     "description": "Memory currently used by InnoDB buffer pool to store cached data pages.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_status_buffer_pool_pages{state=\"data\", rems_application_group=\"$ApplicationGroup\", rems_service=\"$Service\"} * 16 / 1024",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Buffer Pool Free Memory",
     "type": "stat",
     "description": "Number of unused pages available in the InnoDB buffer pool that can be used to cache new data.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mysql_global_status_buffer_pool_pages{state=\"free\", rems_application_group=\"$ApplicationGroup\", rems_service=\"$Service\"} * 16 / 1024",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Network Traffic",
     "type": "timeseries",
     "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mysql_global_status_bytes_received{ rems_application_group=\"$ApplicationGroup\", rems_service=\"$Service\"}[$__rate_interval]))",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mysql_global_status_bytes_sent{ instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  }
 ]
}