{
 "title": "Redis",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x, it works with helm stable/redis-ha exporter.\r\n\r\nIf you missing redis memory utilization, please modify \"maxmemory\" value in values.yaml",
 "tags": [
  "redis",
  "ot-dashboard"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Redis Health & Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "gauge",
   "description": "Measures how long the Redis pod has been running.\t",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_uptime_in_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Health",
   "type": "stat",
   "description": "It Shows the redis health",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"redis-redis-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slaves_Connected",
   "type": "stat",
   "description": "Measures how long the Redis pod has been running.\t",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_connected_slaves", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Replication Lag P1",
   "type": "timeseries",
   "description": "Represents the current replication offset, which is the total number of bytes sent by the primary to all replicas.",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "redis_master_repl_offset", "legendFormat": "__auto" }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Used Memory",
   "type": "bargauge",
   "description": "Measures the memory usage by Redis in bytes.\t",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "__auto" },
    { "expr": "redis_memory_peak_bytes", "legendFormat": "__auto" },
    { "expr": "redis_memory_rss_bytes", "legendFormat": "__auto" },
    { "expr": "redis_memory_lua_bytes", "legendFormat": "__auto" },
    {
     "expr": "redis_memory_fragmentation_ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Peak",
   "type": "stat",
   "description": "Highest memory usage since the last Redis restart.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_peak_bytes /1024/1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory limit",
   "type": "stat",
   "description": "Maximum memory Redis is allowed to use",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_max_bytes /1024 /1024/1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage %",
   "type": "gauge",
   "description": "Percentage of allowed memory currently in use.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(redis_memory_used_bytes / redis_memory_max_bytes) * 100\n",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Memory Fragmentation",
   "type": "stat",
   "description": "Ratio between allocated memory and actual OS memory usage.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_mem_fragmentation_ratio\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Memory LUA",
   "type": "stat",
   "description": "Memory used by Redis Lua scripts.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_memory_used_lua_bytes\n", "legendFormat": "__auto" }
   ]
  },
  { "title": "Client & Connection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Connected Client",
   "type": "stat",
   "description": "The number of connected clients to Redis.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rejected-Connection",
   "type": "stat",
   "description": "Tracks connections rejected due to max clients or resource issues.\t",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(redis_rejected_connections_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "blocked client",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_blocked_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "maximum client",
   "type": "timeseries",
   "description": "Maximum number of client connections allowed",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "targets": [
    { "expr": "redis_config_maxclients\n", "legendFormat": "__auto" }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Commands Executed  ",
   "type": "gauge",
   "description": "Tracks the total commands executed by Redis per sec.\t",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_commands_processed_total\n",
     "legendFormat": "command"
    }
   ]
  },
  {
   "title": "Evicted Keys",
   "type": "timeseries",
   "description": "Keys removed because memory limit was reached.",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 25 },
   "targets": [
    {
     "expr": "rate(redis_evicted_keys_total[1m])\n",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Expired Keys",
   "type": "timeseries",
   "description": "Keys automatically deleted due to TTL expiry.",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "rate(redis_expired_keys_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "clients_blocked",
   "type": "stat",
   "description": "Number of blocked clients waiting for operations to complete.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_blocked_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Keyspace Hits / Misses per Sec ",
   "type": "timeseries",
   "description": "Measures the number of successful key lookups in Redis./ Measures the number of failed key lookups in Redis.\t",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keyspace Miss",
   "type": "timeseries",
   "description": "Number of failed key lookups",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "rate(redis_keyspace_misses_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Keys",
   "type": "gauge",
   "description": "Number of keys currently active in Redis, excluding keys that are set to expire.",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_db_keys) by (instance)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O P3",
     "type": "timeseries",
     "description": "Rate of incoming and outgoing network traffic.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "rate(redis_client_recent_max_input_buffer_bytes[5m])",
       "legendFormat": "I/O"
      },
      {}
     ]
    },
    {
     "title": "Client Input Buffer",
     "type": "timeseries",
     "description": "Rate of incoming network traffic.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "redis_client_recent_max_input_buffer_bytes",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Client Output Buffer",
     "type": "timeseries",
     "description": "Displays memory consumed by client output buffers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "redis_client_recent_max_output_buffer_bytes",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}