{
 "title": "AWS VPC Cost Analytics",
 "tags": [
  "aws ",
  "cost",
  "analytics"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClickHouse", "query": "grafana-clickhouse-datasource" },
   {
    "name": "account_name",
    "query": "SELECT DISTINCT \n  account_name as __text,\n  account_name as __value\nFROM cost.service_costs \nWHERE account_name IS NOT NULL\nORDER BY account_name;"
   }
  ]
 },
 "panels": [
  {
   "title": "Daily VPC Cost Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "cost",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  toDate(usage_start_ts) AS date,\n  round(sum(cost_blended), 2) AS total_vpc_cost,\n  min(usage_start_ts) as min_ts,\n  max(usage_start_ts) as max_ts\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\nGROUP BY date\nORDER BY date\n\n\n",
     "rawQuery": "/* grafana dashboard=AWS EBS Cost Analytics, user=1 */\nSELECT\n  toDate(usage_start_ts) AS date,\n  round(sum(cost_blended), 2) AS total_vpc_cost,\n  min(usage_start_ts) as min_ts,\n  max(usage_start_ts) as max_ts\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\nGROUP BY date\nORDER BY date",
     "rawSql": "SELECT\n  toDate(usage_start_ts) AS time,\n  account_name AS metric,\n  SUM(cost_blended) AS _\nFROM cost.service_costs\nWHERE\n  $__timeFilter(usage_start_ts)\n  AND product_code = 'AmazonVPC'\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY\n  time,\n  metric\nORDER BY\n  time",
     "round": "0s"
    }
   ]
  },
  {
   "title": "High-Level Cost View ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Account ID",
     "type": "piechart",
     "description": "VPC cost on the basis of account ids",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    concat('Account ID -', cast(account_id AS String)) AS metric,\n    round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n",
       "rawQuery": "/* grafana dashboard=AWS VPC Cost Analytics, user=1 */\nSELECT\n    concat('Account ID -', cast(account_id AS String)) AS metric,\n    round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\nGROUP BY metric\nORDER BY value DESC",
       "rawSql": "SELECT\n  concat('Account Name: ', account_name) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY account_name, metric\nORDER BY value DESC\n\n\n\n\n\n",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Region",
     "type": "piechart",
     "description": "Cost Comparison Across Regions",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  region AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\nGROUP BY region\nORDER BY value DESC\n\n",
       "rawQuery": "/* grafana dashboard=AWS RDS Cost Analytics, user=1 */\nSELECT\n  region AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\nGROUP BY region\nORDER BY value DESC",
       "rawSql": "SELECT\n  region AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY region\nORDER BY value DESC\n\n\n\n",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Availability Zones",
     "type": "piechart",
     "description": "VPC cost on the basis of Availability Zones",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  availability_zone AS metric,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND trimBoth(availability_zone) != ''\nGROUP BY metric\nORDER BY total_cost DESC\n\n\n\n",
       "rawQuery": "/* grafana dashboard=AWS VPC Cost Analytics, user=1 */\nSELECT\n  availability_zone AS metric,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND trimBoth(availability_zone) != ''\nGROUP BY metric\nORDER BY total_cost DESC",
       "rawSql": "SELECT\n  availability_zone AS metric,\n  round(sum(cost_blended), 2) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND trimBoth(availability_zone) != ''\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY metric\nORDER BY total_cost DESC\n",
       "round": "0s"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation & Usage Cost Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": " Cost by Usage Type",
     "type": "piechart",
     "description": "VPC cost on the basis of  Usage Type",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "dateTimeColDataType": "usage_start_ts",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  trim(instance_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND instance_family IS NOT NULL\n  AND trim(instance_family) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
       "rawQuery": "/* grafana dashboard=AWS VPC Cost Analytics, user=1 */\nSELECT\n  trim(instance_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND instance_family IS NOT NULL\n  AND trim(instance_family) != ''\nGROUP BY metric\nORDER BY value DESC",
       "rawSql": "SELECT \n    usage_type AS usage_category,\n    ROUND(SUM(cost_unblended), 5) AS cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY usage_category\nORDER BY cost DESC\n\n",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Resource ID",
     "type": "piechart",
     "description": "VPC cost on the basis of Resource ID",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "dateTimeColDataType": "usage_start_ts",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  trim(instance_type_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND instance_type_family IS NOT NULL\n  AND trim(instance_type_family) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
       "rawQuery": "/* grafana dashboard=AWS VPC Cost Analytics, user=1 */\nSELECT\n  trim(instance_type_family) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND instance_type_family IS NOT NULL\n  AND trim(instance_type_family) != ''\nGROUP BY metric\nORDER BY value DESC",
       "rawSql": "SELECT \n  resource_id,\n  SUM(cost_unblended) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY resource_id\nORDER BY total_cost DESC\n",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Operation",
     "type": "piechart",
     "description": "VPC cost on the basis of Operation",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "dateTimeColDataType": "usage_start_ts",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  trim(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND instance_type IS NOT NULL\n  AND trim(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
       "rawQuery": "/* grafana dashboard=AWS VPC Cost Analytics, user=1 */\nSELECT\n  trim(instance_type) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND instance_type IS NOT NULL\n  AND trim(instance_type) != ''\nGROUP BY metric\nORDER BY value DESC",
       "rawSql": "SELECT \n  operation,\n  SUM(cost_unblended) AS total_cost\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY operation\nORDER BY total_cost DESC\n",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Pricing Model",
     "type": "piechart",
     "description": "VPC cost on the basis of Pricing Model ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "database": "cost",
       "dateTimeColDataType": "usage_start_ts",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  trim(pricing_model) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND trim(pricing_model) != ''\n  AND pricing_model IS NOT NULL\nGROUP BY metric\nORDER BY value DESC\n\n\n\n",
       "rawQuery": "/* grafana dashboard=AWS VPC Cost Analytics, user=1 */\nSELECT\n  trim(pricing_model) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND trim(pricing_model) != ''\n  AND pricing_model IS NOT NULL\nGROUP BY metric\nORDER BY value DESC",
       "rawSql": "SELECT\n  trim(pricing_model) AS metric,\n  round(sum(cost_blended), 2) AS value\nFROM cost.service_costs\nWHERE product_code = 'AmazonVPC'\n  AND pricing_model IS NOT NULL\n  AND trim(pricing_model) != ''\n  AND $__timeFilter(usage_start_ts)\n  AND account_name IS NOT NULL\n  AND (\n    'All' IN (${account_name}) OR account_name IN (${account_name})\n  )\nGROUP BY metric\nORDER BY value DESC\n\n",
       "round": "0s"
      }
     ]
    }
   ]
  }
 ]
}