{
 "title": "Endpoint Monitoring",
 "description": "The Endpoint Monitoring Dashboard provides real-time visibility into the availability, reliability, and performance of application endpoints across environments. It helps in proactively identifying failures, latency spikes, and unhealthy services before they impact end users.",
 "tags": [
  "ot-dashboard",
  "blackbox",
  "endpoint monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "query": "prometheus" },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(probe_success,rems_environment)"
    }
   },
   {
    "name": "application_group",
    "label": "ApplicationGroup",
    "query": {
     "query": "label_values(probe_success{rems_environment=~\"$env\"},rems_application_group)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(probe_success{rems_environment=~\"$env\", rems_application_group=~\"$application_group\"},rems_service)"
    }
   },
   {
    "name": "instance",
    "label": "Endpoints",
    "query": {
     "query": "label_values(probe_success{rems_environment=~\"$env\", rems_application_group=~\"$application_group\", rems_service=~\"$service\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Endpoints Success Rate",
   "type": "grafana-polystat-panel",
   "description": "Endpoints in current cluster",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{rems_environment=\"$env\", rems_application_group=~\"$application_group\", rems_service=~\"$service\", instance=~\"$instance\"}[$__rate_interval]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Endpoint Success Rate",
   "type": "timeseries",
   "description": "Endpoint success rate",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{rems_environment=\"$env\", rems_application_group=~\"$application_group\", rems_service=~\"$service\", instance=~\"$instance\"}[$__rate_interval]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "timeseries",
   "description": "HTTP Status",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "probe_http_status_code{rems_environment=\"$env\", rems_application_group=~\"$application_group\", rems_service=~\"$service\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "description": "<p><strong>Instance</strong> – The endpoint URL being probed.</p><p><strong>Status</strong> – Indicates whether the probe is UP or DOWN.</p><p><strong>Code</strong> – HTTP response code returned by the service.</p><p><strong>SSL</strong> – Shows whether SSL/TLS is enabled and valid.</p><p><strong>TLS Version</strong> – The TLS protocol version used for HTTPS.</p><p><strong>SSL Cert Expiry (days)</strong> – Days remaining before the SSL certificate expires.</p><p><strong>SSL Cert Expiry Color Rules</strong> – (-365 to 7 days → <span style='color:red;font-weight:bold;'>Red</span>, 8 to 15 days → <span style='color:#EAB839;font-weight:bold;'>Yellow</span>, 16+ days → <span style='color:green;font-weight:bold;'>Green</span>)</p><p><strong>Probe Duration (s)</strong> – Total time taken for the HTTP probe to complete.</p><p><strong>DNS Lookup Duration (s)</strong> – Time taken for DNS resolution.</p>",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max by (instance,rems_application_group, rems_service) (\n  probe_success{\n    rems_environment=\"$env\",\n    rems_application_group=~\"$application_group\",\n    rems_service=~\"$service\",\n    instance=~\"$instance\"\n  }\n)"
    },
    {
     "expr": "max by (instance, rems_application_group, rems_service) (\n  (probe_ssl_earliest_cert_expiry{\n    rems_environment=\"$env\",\n    rems_application_group=~\"$application_group\",\n    rems_service=~\"$service\",\n    instance=~\"$instance\"\n  } - time()) / 3600 / 24\n)"
    },
    {
     "expr": "max by (instance, rems_application_group, rems_service) (\n  (probe_ssl_earliest_cert_expiry{\n    rems_environment=\"$env\",\n    rems_application_group=~\"$application_group\",\n    rems_service=~\"$service\",\n    instance=~\"$instance\"\n  } - time()) / 3600 / 24\n)"
    },
    {
     "expr": "max by (instance, rems_application_group, rems_service) (\n  probe_http_status_code{\n    rems_environment=\"$env\",\n    rems_application_group=~\"$application_group\",\n    rems_service=~\"$service\",\n    instance=~\"$instance\"\n  }\n) > 0"
    },
    {
     "expr": "max by (instance, rems_application_group, rems_service) (\n  avg_over_time(\n    probe_duration_seconds{\n      rems_environment=\"$env\",\n      rems_application_group=~\"$application_group\",\n      rems_service=~\"$service\",\n      instance=~\"$instance\"\n    }[1m]\n  )\n)"
    },
    {
     "expr": "probe_tls_version_info{rems_environment=\"$env\", rems_application_group=~\"$application_group\", rems_service=~\"$service\", instance=~\"$instance\"}"
    },
    {
     "expr": "max by (instance, rems_application_group, rems_service) (\n  avg_over_time(\n    probe_dns_lookup_time_seconds{\n      rems_environment=\"$env\",\n      rems_application_group=~\"$application_group\",\n      rems_service=~\"$service\",\n      instance=~\"$instance\"\n    }[1m]\n  )\n)"
    }
   ]
  }
 ]
}